### ISSUE TITLE
Groovy DSL dependencies can take collections, Kotlin DSL dependencies should as well

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#1187] opened 2018-10-17 03:47 UTC
In the Groovy DSL, the following is valid:
```gradle
dependencies {
    def junit = [
            "org.junit.jupiter:junit-jupiter-api:5.2.0",
            "org.junit.jupiter:junit-jupiter-engine:5.2.0",
            "org.junit.jupiter:junit-jupiter-params:5.2.0"
    ]
    compile junit
}
```
The following in the Kotlin DSL is not valid:
```
dependencies {
    val junit = listOf(
            "org.junit.jupiter:junit-jupiter-api:5.2.0",
            "org.junit.jupiter:junit-jupiter-engine:5.2.0",
            "org.junit.jupiter:junit-jupiter-params:5.2.0"
    )
    compile(junit)
}
```

This gives the following exception:
```
Cannot convert the provided notation to an object of type Dependency: [org.junit.jupiter:junit-jupiter-api:5.2.0, org.junit.jupiter:junit-jupiter-engine:5.2.0, org.junit.jupiter:junit-jupiter-params:5.2.0].
The following types/formats are supported:
  - Instances of Dependency.
  - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
  - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
  - FileCollections, for example files('some.jar', 'someOther.jar').
  - Projects, for example project(':some:project:path').
  - ClassPathNotation, for example gradleApi().

Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.
```

The Groovy version works because of the `DefaultDependencyHandler` implements `MethodMixIn` and exposes some dynamic methods that automatically iterate over any collections when collections or arguments are passed.
 
https://github.com/gradle/gradle/blob/b28f3cd61af791af1ad87b20c5d41b0624c34a39/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DynamicAddDependencyMethods.java#L43-L63

I'm happy to PR to fix this, but the question I have is if this should be fixed in the Kotlin DSL generated methods or if it should be fixed in the `DefaultDependencyHandler` propper.

IE: should `DefaultDependencyHandler::add` support taking collections or should the Kotlin DSL generated methods detect that the argument passed is a collection and iterate over it?

### Context
Trying to add extension function that apply a group of dependencies in such a way that works in both the Groovy and Kotlin DSL.

For example:
```
plugins {
    id ("my-awesome-plugin")
}
dependencies {
    compile(someDependenciesNeededByMyPlugin())
}
```

Where `someDependenciesNeededByMyPlugin` is something like:
```kotlin
val someDependenciesNeededByMyPlugin = object : Callable<List<String>> {
    override fun call(): List<String> {
        return listOf(
                "org.junit.jupiter:junit-jupiter-api:5.2.0",
                "org.junit.jupiter:junit-jupiter-engine:5.2.0",
                "org.junit.jupiter:junit-jupiter-params:5.2.0"
        )
    }
}

(project.dependencies as ExtensionAware)
    .extensions.add(
        typeOf<Callable<List<String>>>(),
        "someDependenciesNeededByMyPlugin",
        someDependenciesNeededByMyPlugin)
```

### Your Environment
```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.13.6 x86_64

```

**Comment by eskatos** [comment] 2018-11-05 15:31
This feature should be supported by the Gradle API. It should also work from e.g. Java. The fix should happen in `gradle/gradle`.

**Comment by eskatos** [comment] 2018-11-06 16:19
That's a duplicate of #639, closing

**Closed by eskatos** 2018-11-06 16:19 UTC
Labels: a:feature, help wanted, in:gradle-api, re:groovy-parity
