### ISSUE TITLE
Unexpected native library version loaded. Expected 24, was 19.

### ISSUE THREAD

**Issue by metjka** [gradle/kotlin-dsl#309] opened 2017-03-18 12:41 UTC
I keep getting this issue while tring to refresh my gradle project.
I am using linux with oracle-jdk8 

Gradle 'vortex' project refresh failed
Error:Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.5-20170305000422+0000/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

FAILURE: Build failed with an exception.

* What went wrong:
Unexpected native library version loaded. Expected 24, was 19.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by diego-rocha-movile** [comment] 2017-03-21 04:09
I erased my `~/.gradle` folder and it worked. It was somehow mixing up native-platform versions.

This seems to be a problem with gradle itself rather gradle-script-kotlin.

**Comment by metjka** [comment] 2017-03-22 18:41
@diego-rocha-movile it worked. Thanks for the tip!

**Comment by bamboo** [comment] 2017-08-23 09:18
Closed as non reproducible, please reopen if you find a small repro.

**Closed by bamboo** 2017-08-23 09:18 UTC

**Comment by lusvelt** [comment] 2018-01-03 22:39
I deleted ~/.gradle folder, but it still logs me the error `Unexpected native library version loaded. Expected 21, was 25.`

**Comment by bamboo** [comment] 2018-01-04 00:17
Hi @lusvelt, would you mind opening a new issue to provide more details about the error you're experiencing?

**Comment by SimonLammer** [comment] 2018-01-12 07:56
having the same problem as @lusvelt:
```
[slammer:~]$ gradle --version   

FAILURE: Build failed with an exception.

* What went wrong:
Unexpected native library version loaded. Expected 21, was 25.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by kishankumawat** [comment] 2018-02-18 17:15
just remove gradle and reinstall using apt-get install gradle

**Comment by carlos-mg89** [comment] 2018-03-01 13:26
Thanks for your tip @SimonLammer , removing gradle and installing it using sdk (I'm on Linux) worked perfectly well to remove that annoying error.

**Comment by Jaciss** [comment] 2018-05-09 21:41
I had the same

`Unexpected native library version loaded. Expected 21, was 25.`

error and lack of debug output.  I assumed it was due to an outdated Ubuntu package and went the route of updating gradle by adding a more recent ppa:

`sudo add-apt-repository ppa:cwchien/gradle`
`sudo apt-get update`
`sudo apt upgrade gradle`

And I no longer get the error.
