### ISSUE TITLE
Potential `gradle-kotlin-dsl-accessors.jar` file handler leak

### ISSUE THREAD

**Issue by blindpirate** [gradle/kotlin-dsl#1086] opened 2018-08-31 09:09 UTC
### Context

Today I observed two failures on my branch:

https://builds.gradle.org/viewLog.html?buildId=15407726&buildTypeId=Gradle_Check_Platform_Java8_Oracle_Windows_integTest

It seems that `gradle-kotlin-dsl-accessors.jar` is not closed properly. I logged to the build agent and searched the file, it seemed to be held by a daemon which is forked during the test (I failed to check the process command line arguments because it's killed quickly by cleanup step of the build).

Maybe there's a file leak in the daemon after the build finishes.

**Comment by eskatos** [comment] 2018-08-31 10:26
The accessors jar is the sole usage of the kotlin embedded compiler that produces a jar file, other usages produce classes dirs.

**Comment by eskatos** [comment] 2018-08-31 10:26
@blindpirate confirmed the file is held by the Gradle daemon, not by the kotlin compiler daemon:

![image](https://user-images.githubusercontent.com/132773/44907688-1735f580-ad19-11e8-8161-824dccc36d0a.png)

**Comment by bamboo** [comment] 2018-08-31 13:34
> Maybe there’s a file leak in the daemon after the build finishes.

The `KotlinScriptClassloadingCache` service outlives builds because it's a user home scoped service:

https://github.com/gradle/kotlin-dsl/blob/3f89856909d270ed29bc97b061daa0f17c92629e/subprojects/provider/src/main/kotlin/org/gradle/kotlin/dsl/provider/GradleUserHomeServices.kt#L27

One of the cached ClassLoaders is most likely holding the jar open.

The `tearDown` of the offending test should make sure the daemon is gone before trying to delete the test directory, or at the very least that all ClassLoaders have been disposed of.

**Comment by eskatos** [comment] 2018-09-11 10:41
Closing as fixed by #1093

**Closed by eskatos** 2018-09-11 10:41 UTC
Labels: a:bug, in:kotlin-dsl-runtime
