### ISSUE TITLE
Project generated by apply<IdeaPlugin>() is all red

### ISSUE THREAD

**Issue by stanislaw89** [gradle/kotlin-dsl#165] opened 2016-10-24 19:31 UTC
When I import hello-world sample by IDEA everything is working fine(nice code completion, javadocs etc). 
But when I added "apply<org.gradle.plugins.ide.idea.IdeaPlugin>()" into the build.gradle.kts file and generated IDEA's project by ./gradlew idea and opened hello-world.ipr everything becomes red:
<img width="650" alt="screenshot 2016-10-24 22 19 16" src="https://cloud.githubusercontent.com/assets/3681384/19660381/3244380a-9a38-11e6-813f-b757f0e57718.png">

In my project I use ./gradlew idea instead of standard IDEA importer because IDEA importer ignores configuration like:

``` groovy
 idea {
   project {
        ipr {
            ideaImportCodeStyle(it, file("idea-code-style.xml"))
            ideaInspectionProfiles(it, file("idea-inspections.xml"))
        }
    }
    module {
        iml {
            ideaAddWebFacet(it, "server.war", "src/main/webapp")
        }
    }
}  
```

Maybe I can enable kotlin support by IDEA without importing project through IDEA importer?

**Comment by eskatos** [comment] 2017-12-23 13:07
See https://youtrack.jetbrains.com/issue/KT-19025

**Comment by eskatos** [comment] 2018-01-18 10:00
Closing as duplicate of #643

**Closed by eskatos** 2018-01-18 10:00 UTC
