### ISSUE TITLE
Can't use variables in plugins block when package is set in buildSrc

### ISSUE THREAD

**Issue by lukekoko0909** [gradle/kotlin-dsl#1374] opened 2019-04-18 18:49 UTC
I have Versions.kt file (buildSrc) in wchich I specify versions of libraries and plugins. I can't use them in plugins block if package is set. Please check plugins block in the build.gradle.kts file in root of the project.

### Expected Behavior
I would like example from "Current Behavior.1" to work :)

### Current Behavior
1.  **Does not work** 
code from root build.gradle.kts file
**with** package set in Versions.kt
` id("org.springframework.boot") version Versions.springBoot `

2.  **Works**
code from root build.gradle.kts file
**without** package set in Versions.kt
` id("org.springframework.boot") version Versions.springBoot `

### Context
I would like to have one constant way to set versions of all plugins and dependencies across entire project. This is important especially when you have a lot of modules.

### Steps to Reproduce (for bugs)
[demoApp.zip](https://github.com/gradle/kotlin-dsl/files/3095774/demoApp.zip)

### Your Environment
 * gradle version = 5.4
 * Version of IntelliJ = 2019.1.1 Ultimate
 * Version of the Kotlin Plugin used in IntelliJ = 1.3.30-release-IJ2019.1-1

**Comment by eskatos** [comment] 2019-04-25 12:54
Closing as a duplicate of https://github.com/gradle/kotlin-dsl/issues/939

**Closed by eskatos** 2019-04-25 12:54 UTC
Labels: was:duplicate
