### ISSUE TITLE
KT-25366: Kotlin DSL in IntelliJ under JDK 10 is covered in errors

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#888] opened 2018-05-22 00:16 UTC
### Expected Behavior
The Kotlin DSL should render without any errors the same way it does for JDK 8.

### Current Behavior
<img width="572" alt="screenshot 2018-05-21 20 13 05" src="https://user-images.githubusercontent.com/1323708/40335766-789712c2-5d33-11e8-823d-5eff0f2b92c4.png">

The red underlines seem to be warnings not errors. It doesn't have any impact on jumping to declarations or autocomplete support.

### Steps to Reproduce (for bugs)
Try to load a Kotlin DSL project in IntelliJ Ultimate with JDK 10.

### Your Environment
```
------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          10.0.1 ("Oracle Corporation" 10.0.1+10)
OS:           Mac OS X 10.13.4 x86_64

IntelliJ IDEA 2018.1.4 (Ultimate Edition)
Build #IU-181.5087.20, built on May 16, 2018
Licensed to Ktlint Gradle / Jonathan  Leitschuh
Subscription is active until January 22, 2019
For non-commercial open source development only.
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4
```

### YouTrack Issue
https://youtrack.jetbrains.com/issue/KT-25366

**Comment by JLLeitschuh** [comment] 2018-05-30 16:03
@eskatos Is this a Gradle issue or a Jetbrains issue? If so, I should open an issue with Jetbrains.

**Comment by eskatos** [comment] 2018-06-20 13:46
It looks jigsaw related. If it's only warnings, then the IDE should show warning signals, not red error ones.

@JLLeitschuh does your build still work (from the CLI and IDE) ?
I assume it does.

**Comment by JLLeitschuh** [comment] 2018-06-20 21:50
It works from the CLI, I haven't tried from the IDE.

@gftabor or @SamCarlberg can you execute the PathUI tasks in IntelliJ IDE under JDK 10 or can you only do it from the command line?

**Comment by SamCarlberg** [comment] 2018-06-20 21:54
Running Gradle tasks via IntelliJ run configurations works fine on JDK 10.

**Comment by eskatos** [comment] 2018-06-22 07:27
The message seems to come from Kotlin compiler diagnostics where errors/warnings aren't distinguished: https://github.com/JetBrains/kotlin/blob/cffe7fb23ba7bce612876f88ce33b29bf75be02f/compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/diagnostics/DefaultErrorMessagesJvm.java#L129

It looks like the IntelliJ Kotlin script editor has Jigsaw modules checks enabled when editing Gradle scripts. Or something along those lines.

@JLLeitschuh could you please open an issue on JetBrains KT Youtrack? I'm sure Kotlin folks will know what is happening better.

**Comment by eskatos** [comment] 2018-07-24 17:20
@JLLeitschuh, could you please follow up on https://youtrack.jetbrains.com/issue/KT-25366#comment=27-2945940? I can't reproduce either.

**Comment by JLLeitschuh** [comment] 2018-08-01 16:01
I can't reproduce this with Gradle 4.9.
It must have been problems exclusive to earlier versions of Gradle.

**Comment by SamCarlberg** [comment] 2018-08-01 16:26
@JLLeitschuh I have two simple Gradle 4.9 projects that exhibit this behavior. This problem seems to  appear when a module-info.java file is present in the source root.

**Comment by JLLeitschuh** [comment] 2018-08-01 18:39
@SamCarlberg Can you link to them?

**Comment by sureshg** [comment] 2018-08-06 00:36
I am having same kind of issues in Intellij with the latest kotlin plugin and `JDK 10`

<img width="934" alt="screen shot 2018-08-05 at 5 29 57 pm" src="https://user-images.githubusercontent.com/356994/43691702-3ab814e6-98d5-11e8-9be4-2454811996d7.png">

Sample project : https://github.com/sureshg/kotlin-scratchpad (Import this project and change the java version to `10`)

Java Version: `jdk-10.0.1`
Kotlin/Plugin Version: `1.2.60`
Gradle version: `4.9`

Intellij Version
--------------
```
IntelliJ IDEA 2018.2.1 (Ultimate Edition)
Build #IU-182.3911.13, built on July 30, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5
```

**Comment by corlip** [comment] 2018-11-04 09:17
I have the same issue.

Very small example project:
[kotlindslerror.zip](https://github.com/gradle/kotlin-dsl/files/2545685/kotlindslerror.zip)

Output of IntelliJ/Gradle Versions:

>IntelliJ IDEA 2018.2.5 (Community Edition)
>Build #IC-182.4892.20, built on October 16, 2018
>JRE: 1.8.0_152-release-991-b1 amd64
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
>Linux 3.10.0-862.14.4.el7.x86_64
>Gradle 4.9
>Kotlin DSL:   0.18.4
>Kotlin:       1.2.41

**Comment by eskatos** [comment] 2018-12-11 10:10
Closed as obsolete upstream

**Closed by eskatos** 2018-12-11 10:10 UTC
Labels: a:bug, by:jetbrains, in:kt-idea-plugin, re:editing
