### ISSUE TITLE
project.name = "xx" cannot be assigned

### ISSUE THREAD

**Issue by StefMa** [gradle/kotlin-dsl#742] opened 2018-03-05 13:53 UTC
### Expected Behavior
`rootProject.name = "xx"` should compile in `settings.gradle.kts`

### Current Behavior
I can't change the project name:
![bildschirmfoto 2018-03-05 um 14 51 41](https://user-images.githubusercontent.com/10229883/36978431-c092d94e-2084-11e8-8a11-59abf7e583f9.png)

### Context
I've just created a new Gradle/Kotlin project in IntelliJ.
The default groovy `settings.gradle` have the autogenerated code 
```
rootProject.name = "Gloc"
```
If i change this file to `settings.gradle.kts` it says the issue above...

### Steps to Reproduce (for bugs)
See above ☝️ 

Maybe this is similar to #712 
But I can't find a `rootProject.setName("xx")` :/

**Comment by tbroyer** [comment] 2018-03-05 16:03
Are you sure it's not #685?

**Comment by StefMa** [comment] 2018-03-05 16:09
Don't know if it's the same...
But I use the latest kotlin version and have that issue...

**Comment by JLLeitschuh** [comment] 2018-03-05 18:22
Is this only an issue in IntelliJ or when you execute the script with Gradle do you also get a compilation error?

**Comment by StefMa** [comment] 2018-03-06 07:19
@JLLeitschuh just checked it and it really seems just a IDE issue.
If I add the code and do a `./gradlew clean build --no-build-cache` I got a successfully output.. 👍

**Comment by bamboo** [comment] 2018-03-06 13:43
Thanks, everyone!

Closing as duplicate of #685

**Closed by bamboo** 2018-03-06 13:43 UTC
