### ISSUE TITLE
How to read a val in plugins {}

### ISSUE THREAD

**Issue by redtankd** [gradle/kotlin-dsl#802] opened 2018-03-30 14:54 UTC
```
val kotlinVersion = "1.2.31"

plugins {
    kotlin("jvm")           version $kotlinVersion apply false
    kotlin("plugin.spring") version $kotlinVersion apply false
}
```

gradle report "Unresolved reference: kotlinVersion"

**Comment by JLLeitschuh** [comment] 2018-03-30 20:20
The `plugins`block is special, you can't read variables inside of it.
You can use the `pluginResolution` block in the `settings` file to use variables from properties and things like that.

**Comment by eskatos** [comment] 2018-04-03 15:16
Closing as duplicate of #158

**Closed by eskatos** 2018-04-03 15:16 UTC
Labels: a:question, was:duplicate

**Comment by StefMa** [comment] 2018-04-13 06:33
@ice1000 
I bet you want to reuse the kotlin variable because you need it for the kotlin dependency, right? 
In my current project I have the following setup:
(It is in Groovy, but you can archive the same with Kotlin I think)

`buildSrc/src/main/kotlin/some/package/Version.kt`:
```
object Versions {

    object Plugin {
        val kotlin = "1.2.31"
    }

    object Dependency {
        val kotlin = = Plugin.kotlin
    }
}
```

`settings.gradle`:
```
import some.package.Versions

pluginManagement {
    repositories {
        gradlePluginPortal()
        jcenter()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.startsWith("org.jetbrains.kotlin.")) {
                it.useVersion(Versions.Plugin.kotlin)
            }
        }
    }
}
```

If you have setup this you can simply omit the version in the plugins block:
```
plugins {
  ...
  kotlin("jvm")
}
```

In your dependency block you can simply say:
```
import some.package.Versions.Dependency 

dependencies {
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$Dependency.kotlin"
}
```

**Comment by ice1000** [comment] 2018-04-13 08:47
Wow cool! I love this, countless thanks! @StefMa
