### ISSUE TITLE
root build.gradle.kts didn't work with buildSrc used in dependencies

### ISSUE THREAD

**Issue by mtrakal** [gradle/kotlin-dsl#1291] opened 2018-12-09 08:55 UTC
When use root `build.gradle.kts` file and inside `buildscript > dependencies` variables from `buildSrc` build failed. When use without `buildSrc` or when not use `kts file` but juts Groovy `build.gradle` variables works.

### Expected Behavior
Build project without failure

### Current Behavior
Fail on 
```
Script compilation errors:

  Line 18:         classpath(Config.BuildPlugins.androidPlugin)
                             ^ Unresolved reference: Config
```

### Steps to Reproduce (for bugs)
Demo project with reproducible bug: https://github.com/mtrakal/kotlinDslbug

Diff file from working to not workign project (rename file and change lines): https://github.com/mtrakal/kotlinDslbug/commit/09a5db46a10ed0c6d30942e3eede8b1787d7721a

### Your Environment
See on demo project

Maybe related with second issue with default namespace: https://github.com/gradle/kotlin-dsl/issues/1088

**Comment by mtrakal** [comment] 2019-01-29 12:53
Gradle 5.1.1 with Gradle DSL, still not working as expected.

```
CONFIGURE FAILED in 4s
Script compilation errors:

  Line 33:         classpath("com.android.tools.build:gradle:${Config.Versions.gradleBuildTools}")
                                                               ^ Unresolved reference: Config

  Line 34:         classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${Config.Versions.kotlinVersion}")
                                                                          ^ Unresolved reference: Config

  Line 35:         classpath("com.google.android.gms:oss-licenses-plugin:${Config.Versions.PlayServices.ossLicensesPlugin}")
                                                                           ^ Unresolved reference: Config

  Line 36:         classpath("com.google.gms:google-services:${Config.Versions.googleServicesVersion}")
                                                               ^ Unresolved reference: Config
```

```
classpath("com.android.tools.build:gradle:${Config.Versions.gradleBuildTools}")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${Config.Versions.kotlinVersion}")
        classpath("com.google.android.gms:oss-licenses-plugin:${Config.Versions.PlayServices.ossLicensesPlugin}")
        classpath("com.google.gms:google-services:${Config.Versions.googleServicesVersion}")
```

**Comment by mtrakal** [comment] 2019-01-29 13:09
same as: https://github.com/gradle/kotlin-dsl/issues/939
https://github.com/gradle/kotlin-dsl/issues/1319

same for plugins block:

```
plugins {
    id("com.gradle.build-scan") version cz.bs.Config.Versions.buildScanVersion
}
```
vs
```
import cz.bs.Config;

plugins {
    id("com.gradle.build-scan") version Config.Versions.buildScanVersion
}
```

**Comment by luxmeter** [comment] 2019-04-03 20:55
Any progress here? Is there a workaround something like that?

**Comment by mtrakal** [comment] 2019-04-04 11:21
@luxmeter workaround is on my previous comment... 🙃

**Comment by dbaelz** [comment] 2019-04-06 12:20
Fully qualified in this context means, that you can't import the package and use only the class name. So for the above example, it must be `cz.bs.Config.BuildPlugins.androidPlugin` instead of importing the `cs.bz` package and use only `Config.BuildPlugins.androidPlugin` for the variable name.

See also the documentation of Java for package names: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by eskatos** [comment] 2019-04-24 16:12
Closing as duplicate of https://github.com/gradle/kotlin-dsl/issues/939

**Closed by eskatos** 2019-04-24 16:12 UTC
Labels: was:duplicate
