### ISSUE TITLE
Use of project property as opt-in toggle for build caching of scripts is cumbersome in practice

### ISSUE THREAD

**Issue by ldaley** [gradle/kotlin-dsl#1032] opened 2018-08-12 23:46 UTC
### Expected Behavior

A convenient and idiomatic way to opt-in to this functionality on a per user or per project basis.

### Current Behavior

I can either explicitly add the project property to the invocation, which is cumbersome, or use some obtuse `ORG_GRADLE_PROJECT_org.gradle.kotlin.dsl.caching.buildcache=true` env var.

I should have the same options for enabling this as I do for build cache (probably minus the first class invocation option).  That is, I should be able to put something in my «GRADLE_USER_HOME»/gradle.properties or the same file in the project root, as I can with `org.gradle.caching`.

**Comment by ldaley** [comment] 2018-08-12 23:56
If we do change this, also need to update here: https://github.com/gradle/gradle/blob/4d620bab0fdecbc990ebc8c02775ea230578d06a/subprojects/core/src/main/java/org/gradle/internal/scan/config/BuildScanPluginCompatibility.java#L69

**Comment by eskatos** [comment] 2018-08-13 07:27
The following in a `gradle.properties` file should work already:

```properties
org.gradle.project.org.gradle.kotlin.dsl.caching.buildcache=true
```

**Comment by ldaley** [comment] 2018-08-13 09:54
@eskatos if you can turn that `should` into `does`, then we can close this.

**Comment by eskatos** [comment] 2018-08-13 10:38
@ldaley it doesn't work because the property is checked on `StartParameter` which doesn't resolve properties from `gradle.properties` 

https://github.com/gradle/kotlin-dsl/blob/b9cb04969dab25fdf549de5b32231fc6326883f4/subprojects/provider/src/main/kotlin/org/gradle/kotlin/dsl/cache/BuildServices.kt#L49-L50

This needs to be fixed.

**Comment by eskatos** [comment] 2018-08-13 10:57
We should not make that flag a public build option. Its purpose is to test drive script compilation caching during the RC phase. The plan is to get rid of it and simply tie enabling script compilation caching to enabling the build cache.

Making it a project property means one could enable/disable it per project, which is not the desired behavior. Moreover, the script compilation build cache service is build scoped and doesn't have enough context to honor the flag on each invocation.

I think that using a system property instead would better capture the intent.

I confirmed that it can also be set in a `gradle.properties`  file, e.g.

```properties
systemProp.org.gradle.kotlin.dsl.caching.buildcache=true
```

and is then available when we need it to setup the script compilation cache.

@bamboo wdyt?

**Comment by bamboo** [comment] 2018-08-13 12:45
> Making it a project property means one could enable/disable it per project, which is not the desired behavior. 

The property was modelled after the [`org.gradle.caching` project property](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties) but I missed that reading the property from `StartParameter` wouldn't honour `gradle.properties`.

`ScriptCache` could read the property from the target and then it would.

@eskatos It seems more consistent with `org.gradle.caching` to keep it as a project property and fix the behaviour by reading the property from the target project.

**Comment by eskatos** [comment] 2018-08-13 12:48
IIUC `org.gradle.caching` is a Gradle property bound to a build option, not a [Project property](https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties).

**Comment by eskatos** [comment] 2018-08-14 12:34
Follow up PR https://github.com/gradle/gradle/pull/6378 has been merged
Closing

**Closed by eskatos** 2018-08-14 12:34 UTC
Labels: a:bug, in:kotlin-dsl-runtime
