### ISSUE TITLE
Cannot build multi-module project

### ISSUE THREAD

**Issue by honglili-qochealth** [gradle/kotlin-dsl#499] opened 2017-09-20 16:42 UTC
### Expected Behavior

Build failed with multi-module setup (**Unresolved reference: compile**). Current setup worked with gradle **4.0.2**. I've noticed that project-schema.json location has changed with recent gradle distribution. Tried using gradlew gskGenerateAccessors, **project-schema.json** was created under **ROOTPROJECT/buildSrc/src/gradle-script-kotlin**. I remember seeing change logs that states latest gradle reads project-schema.json from **gradle** folder. Not sure if this is what caused the issue.

### Current Behavior

Failed with errors (Unresolved reference: compile, Unresolved reference: testCompile)

### Context

Cannot build multi-module project. Only worked with single module setup with project-schema.json stored under gradle folder.

### Steps to Reproduce (for bugs)

Create gradle project with 2 modules. Run any gradle task will lead to the issues described above.

**Comment by bamboo** [comment] 2017-09-20 16:53
Hi @honglili-qochealth, 

Latest Gradle version does expect `project-schema.json` to be found at `$PROJECT_ROOT/gradle/project-schema.json`.

> Create gradle project with 2 modules. Run any gradle task will lead to the issues described above.

Could you provide such a repro project?

**Comment by honglili-qochealth** [comment] 2017-09-20 17:21
Hi bamboo,
I will provide a repo later. What I've noticed is when there is **`settings.gradle`** file in the project. `gradlew gskGenerateAccessors` will store` project_schema.json` under **`$PROJECT_ROOT/buildSrc/src/gradle-script-ktoin.`** otherwise **`$PROJECT_ROOT/gradle`** folder will be used. Also with single module setup, project_schema.json has **`"configurations"`** section. In multi-module setup. there is no **`"configuration"`** portion in json file.

**Comment by honglili-qochealth** [comment] 2017-09-20 18:46
@bamboo repos created https://github.com/honglili-qochealth/gradle-dsl-multi-module

**Comment by bamboo** [comment] 2017-09-20 18:53
Thanks, @honglili-qochealth!

**Comment by honglili-qochealth** [comment] 2017-09-20 20:14
@bamboo Thanks!

**Comment by honglili-qochealth** [comment] 2017-09-20 20:15
@bamboo Thanks!

**Comment by eskatos** [comment] 2017-09-24 10:10
This happens because of the combination of two things:
1. in [`v0.10.1`](https://github.com/gradle/kotlin-dsl/releases/tag/v0.10.1) we removed the hardcoded extensions for `compile` and `testCompile` configurations in favor of extensions generated from the actual configurations contributed by applied plugins, see #337.
2. you apply plugins imperatively using `apply { plugin("..") }` ; you should prefer using the declarative `plugins {}` block instead to benefit from generated accessors

What you should do is the following:

1. Change your build scripts to use `"compile"`, `"testCompile"` etc... (string references)
2. Update Gradle to 4.2
3. Use the `plugins {}` block to require plugins application
4. Change your build scripts to use `compile`, `testCompile`

I opened a PR against your reproducer project with all these steps as separate commits, this should unblock you: https://github.com/honglili-qochealth/gradle-kotlin-dsl-multi-module/pull/1

I'm going to close this issue, feel free to reopen if you need more guidance.

**Closed by eskatos** 2017-09-24 10:10 UTC
Labels: a:question, re:migration
