### ISSUE TITLE
Introduce unambiguous `PluginAware.apply(Action<ObjectConfigurationAction>)` overloads 

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#682] opened 2018-01-18 18:46 UTC
Because the Kotlin standard library already defines an extension method named `apply` available to any receiver:

```kotlin
inline fun <T> T.apply(block: T.() -> Unit): T
```

And because Kotlin prefers methods applicable to the innermost receiver over methods available to outer receivers (such as the build script itself and its enclosing project), Kotlin's `apply` ends up shadowing [`PluginAware.apply(Action<in ObjectConfigurationAction>)`](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/PluginAware.html#apply-org.gradle.api.Action-).

Any block that implies a receiver that is not `PluginAware` is affected, for instance:

```kotlin
dependencies {
  apply { from("my-dependencies.gradle.kts") } // Unresolved reference: from
}
```

In other words, any invocation of the form `apply { <lambda> }` would match the standard library `apply` extension unless the innermost receiver is `PluginAware`.

We have two options on the table:

1. add simpler overloads for common use-cases that won't conflict with Kotlin's `apply`:

 ```kotlin
 fun PluginAware.apply(from: String, to: Any? = null) = TODO()

 inline
 fun <reified T> PluginAware.apply(to: Any? = null) = TODO() 
```

2. Introduce a different method for Kotlin

**Comment by StefMa** [comment] 2018-01-26 08:07
Hi,

can someone explain me the "issue" here?! I don't really get it. 😥
First of: 
I've never seen a `apply{from("any.gradle")}` inside a `buildscript` block.
How does it differ from the `apply{from("any.gradle")}` from the "top level"? 🤔 

I've also looked into the [`DependencyHandler` interface](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/dsl/DependencyHandler.html) where is no `apply` method.
So from my point of view the issue is not that Kotlin prefers the the receivers somehow.
It is because the `DepencyHandler` don't have a `apply(block: () -> Unit)` method defined which will then - of course - fall back to the extensions function `apply` (from Kotlin).

Basically my question is.
What is different than from:
```
apply {
    from("stuff.gradle")
}

buildscript {
    dependencies {

    }
}
```
to
```
buildscript {
    dependencies {
        project.apply {
            from("stuff.gradle")
        }
    }
}
```

I think nothing, right? 🤔

**Comment by bamboo** [comment] 2018-03-14 18:42
Hi @StefMa,

The `buildscript` block defines the compilation classpath for the outer script and so it is evaluated before the outer script. Thus the second snippet in your comment would apply the `stuff.gradle` script at `buildscript` block evaluation time, still in time to influence the outer script compilation classpath, and the second snippet would apply it at outer script evaluation time.

Your second snippet works around the issue at hand by explicitly qualifying the `apply` function receiver.

And because we don't want to be adding `apply` overloads to every scope we want it to have the _apply plugins_ semantics instead of the Kotlin standard library semantics we are considering the unambiguous overloads described above.

**Comment by eskatos** [comment] 2018-03-16 17:19
Closing as delivered in 99653610643060d5755e4c1e95a1f9c17609f6f6

**Closed by eskatos** 2018-03-16 17:19 UTC
Labels: a:feature, in:kotlin-dsl-api, re:ease-of-use
