### ISSUE TITLE
KT-22210 Use meaningful parameter names instead of `p0`

### ISSUE THREAD

**Issue by sdeleuze** [gradle/kotlin-dsl#464] opened 2017-08-16 13:03 UTC
In IntelliJ IDEA, when you enable the option that displays implicit parameter names, you get weird `p0` parameters in `id()` and `plugin()`. Meaningful parameter names would be better.

![screenshot from 2017-08-16 14-39-13](https://user-images.githubusercontent.com/141109/29364462-c7cb2e3a-8293-11e7-8fd1-f4fdcc738dc5.png)

**Comment by JLLeitschuh** [comment] 2017-08-16 18:31
Is this because gradle is compiled without the `-parameters` compiler flag? This sounds like something that needs to be fixed in the core gradle repository.

https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html

**Comment by eskatos** [comment] 2017-09-27 16:54
> https://github.com/gradle/kotlin-dsl/issues/437#issuecomment-317001913
> Upon further inspection this seems to be caused by Kotlin interface delegation (`... : Project by project { ...`) not preserving the parameter names in the generated bytecode.
>
> Parameter names show up correctly for non delegated members, for instance, notice the version parameter below:
![screen shot 2017-07-21 at 10 32 31 am](https://user-images.githubusercontent.com/51689/28465674-fe24a6da-6dff-11e7-9d67-d0001099da38.png)

**Comment by AlexCzar** [comment] 2017-12-19 08:10
@eskatos I searched Kotlin's issue tracker but couldn't find this specific problem. Was it reported?

**Comment by eskatos** [comment] 2018-01-04 09:55
@AlexCzar not that I know of, feel free to report it upstream, I'll get back to it next week if you don't beat me to it.

It doesn't happen when no `.kts` file is involved.
I didn't try and reproduce outside of the Kotlin DSL yet.

**Comment by eskatos** [comment] 2018-01-10 10:58
Reported upstream: https://youtrack.jetbrains.com/issue/KT-22210

**Comment by bamboo** [comment] 2018-05-22 12:53
Moved to backlog so we can decide if we should tackle it ourselves.

**Comment by eskatos** [comment] 2018-05-24 13:46
Two candidate solutions until Gradle is built with Java 8 and `-parameters`:
- have a parameter names index in the Gradle distribution and enhance the Gradle API Jar before passing it to the Kotlin compiler in the Kotlin DSL build
- building all Gradle modules with Java 8 and `-parameters`, publish them and use them instead of `gradleApi()` in the Kotlin DSL build

**Comment by bamboo** [comment] 2018-06-29 15:37
Tracked it down to https://youtrack.jetbrains.com/issue/KT-25193

**Comment by JLLeitschuh** [comment] 2018-06-29 16:10
Good find!

**Comment by eskatos** [comment] 2018-08-01 08:56
Made an attempt with `-java-parameters` and `-Xuse-old-class-files-reading` in https://github.com/gradle/kotlin-dsl/commit/28cc2ec1f78f9960b98158c0caeaf1ad1e2d7767 without success.

**Comment by eskatos** [comment] 2018-08-01 12:36
Adding `-Xuse-old-class-files-reading` to the small reproducer build works: https://github.com/bamboo/kotlin-parameter-names

To make all this work we'd need the Gradle API jar bytecode to include parameter names.

**Closed** 2018-08-05 13:38 UTC
Labels: a:feature, by:jetbrains, in:gradle-api, in:kotlin-dsl-api, re:content-assist, re:ease-of-use

**Comment by JLLeitschuh** [comment] 2018-08-08 20:18
🎆 🎉 👍 🎉 🎆
