### ISSUE TITLE
Build failed with NoSuchMethodError: KotlinPluginWrapperKt.getKotlinPluginVersion

### ISSUE THREAD

**Issue by johnjohndoe** [gradle/kotlin-dsl#1269] opened 2018-12-03 21:57 UTC
### Expected behavior
- Build succeeds.

### Current behavior
- Build fails with an exception.
``` java
org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapperKt.getKotlinPluginVersion(Lorg/gradle/api/Project;)Ljava/lang/String;
```
- See [this CI build](https://travis-ci.org/EventFahrplan/EventFahrplan/builds/463038856#L1809).

### Context
- I am currently have `id("org.gradle.kotlin.kotlin-dsl") version "0.18.2"` (in `buildSrc`) and `com.android.tools.build:gradle:3.1.1` configured in my [multi-module Android project](https://github.com/EventFahrplan/EventFahrplan).
- I am trying to use `com.android.tools.build:gradle:3.2.1` and whatever version of the `kotlin-dsl` plugin works with it.

### Steps to reproduce
- Checkout this [temporary commit](https://github.com/EventFahrplan/EventFahrplan/commit/31c4efe657ac79ebb4067bcc27f1f759a83a1059)
- Invoke `./gradlew tasks`.

### Your environment
- Gradle wrapper 4.10.2
- Ubuntu 16.04

**Comment by JLLeitschuh** [comment] 2018-12-03 22:11
@johnjohndoe I'd recommend adding the `--stacktrace` flag to your Travis CI build file.

**Comment by StefMa** [comment] 2018-12-04 06:50
As far as I see it correctly you only use some singletons in your buildSrc.
Do you plan more features inside the buildSrc?
Otherwise you don't have to use the "full blown kotlin-dsl" plugin. You can
simply replace it with the default kotlin JVM plugin...

**Comment by johnjohndoe** [comment] 2018-12-04 20:09
@JLLeitschuh Here is the stacktrace:

``` java
java.lang.NoSuchMethodError: org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapperKt.getKotlinPluginVersion(Lorg/gradle/api/Project;)Ljava/lang/String;
        at org.gradle.kotlin.dsl.plugins.embedded.EmbeddedKotlinPlugin.apply(EmbeddedKotlinPlugin.kt:48)
        at org.gradle.kotlin.dsl.plugins.embedded.EmbeddedKotlinPlugin.apply(EmbeddedKotlinPlugin.kt:39)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:174)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
```

**Comment by johnjohndoe** [comment] 2018-12-04 20:21
@StefMa I was using `kotlin-dsl` because the [_kotlin-dsl buildSrc_ samples](https://github.com/gradle/kotlin-dsl/tree/master/samples) have the plugin defined.

**Comment by StefMa** [comment] 2018-12-05 07:41
Wow - you tested a lot 🙃 

Unfounrtaly I don't get a green build because when I checkout the project I always get 
> \> Please create the file 'gradle.properties' before importing the project. Do not forget to add custom values!
Even if I copy the *example stuff...

Anyway. The following build at least my buildSrc:
```kotlin
plugins {
    kotlin("jvm") version "1.3.10"
}

repositories {
    jcenter()
}

dependencies {
    kotlin("stdlib-jdk8")
}
```
**OR**
```kotlin
plugins {
    `kotlin-dsl`
}

repositories {
    jcenter()
}
```

**Comment by johnjohndoe** [comment] 2018-12-05 19:22
@StefMa With regards to the _gradle.properties_ file - the following step should help you to get the project running:

1. `cd /tmp`
2. `git clone --depth 1 https://github.com/EventFahrplan/EventFahrplan.git`
3. `cd EventFahrplan`
4. `cp app/gradle.properties.example app/gradle.properties`
5. `gw tasks`


Your 1. configuration causes the following failure for the whole project build:

> InvalidPluginRequestException: Plugin request for plugin already on the classpath must not include a version

The 2. configuration fails with:
> NoSuchMethodError: org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapperKt.getKotlinPluginVersion(Lorg/gradle/api/Project;)Ljava/lang/String;

**Comment by eskatos** [comment] 2019-04-25 07:57
Each Gradle release is meant to be used with a specific version of the `kotlin-dsl` plugin and compatibility between arbitrary Gradle releases and `kotlin-dsl` plugin versions is not guaranteed.

Using an unexpected version of the `kotlin-dsl` plugin in a build can cause hard to diagnose problems.

Starting with Gradle 5.4, a warning is emitted whenever an unexpected version of the `kotlin-dsl` plugin is detected.

See https://github.com/gradle/gradle/pull/8877

----

Duplicate of
- https://github.com/gradle/kotlin-dsl/issues/1355

**Closed by eskatos** 2019-04-25 07:57 UTC

**Comment by johnjohndoe** [comment] 2019-04-25 08:21
Thank you for your help. One additionally hint: I accidentely had the `buildSrc` folders being added as a `module` in the `settings.xml` which caused weird behaviour. See https://github.com/EventFahrplan/EventFahrplan/commit/5a989058053820152f9985ebf51da805face48a4#diff-88b7c47e47b8ee65263b6784b86fa0a7.
