### ISSUE TITLE
Composite builds cross kotlin-dsl version uses includers version

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#466] opened 2017-08-16 18:47 UTC
This may be totally expected, but maybe not.

If you include another build using the [composite build](https://docs.gradle.org/current/userguide/composite_builds.html) feature the version of the Gradle Kotlin DSL that is used will be the version from the build that is doing the including.

This means that you can't include builds that use API incompatible versions of gradle builds.

### Expected Behavior
If running a build that is running Gradle `4.1` that includes a composite build with code supported by the Gradle `3.5` but not the `4.1` API I expect that I would still be able to include that build.

### Current Behavior

I get exceptions about `compile` and `testCompile` not existing in a dependency block because the older version of gradle had these hard coded but the new version no longer does.

### Steps to Reproduce (for bugs)

Try including this build in a composite build with gradle `4.1`.
(Ensure you are checking out the specific commit, I'm about to update this project to gradle `4.1`)
In particular the lines specified cause the problem.
https://github.com/JLLeitschuh/kotlin-guiced/blob/5c9cce8/kotlin-guiced.gradle.kts#L58-L60

### Your Environment

Gradle version: `4.1`
Included composite build version: `3.5`

**Comment by bigdaz** [comment] 2017-08-16 20:41
A composite build is executed by a single running instance of Gradle: the version of Gradle used is defined by the composing build. As such, all included builds need to be compatible with that version of Gradle.

This is a known limitation, that helped ease the development of the composite build feature, as well as making composite builds no less performant than the equivalent multi-project build.

In the future, we'd like to also support composite builds with heterogeneous Gradle versions.

**Comment by JLLeitschuh** [comment] 2017-08-17 03:15
> This is a known limitation, that helped ease the development of the composite build feature

This totally makes sense and I understand why Gradle made this choice. However, this should probably be documented in the composite build feature page.

**Comment by bamboo** [comment] 2017-08-23 09:25
Closing as _By Design_.

**Closed by bamboo** 2017-08-23 09:25 UTC
