### ISSUE TITLE
Compiling a project with buildSrc fails on IBM JDK 8

### ISSUE THREAD

**Issue by jdanekrh** [gradle/kotlin-dsl#468] opened 2017-08-22 10:30 UTC
Compiling any project with buildSrc fails with exception `e: java.nio.file.ProviderNotFoundException: Provider "jrt" not found`. If I use Oracle JDK or OpenJDK, the compilation succeeds. It fails only with IBM JDK.

### Steps to Reproduce (for bugs)
Switch to IBM JDK

Use any buildSrc sample in this repository, for example

```bash
cd samples/project-with-buildSrc
[vagrant@localhost project-with-buildSrc]$ ./gradlew
e: java.nio.file.ProviderNotFoundException: Provider "jrt" not found
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:352)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:287)
        at org.jetbrains.kotlin.cli.jvm.modules.CoreJrtFileSystem$Companion.create(CoreJrtFileSystem.kt:50)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion$createApplicationEnvironment$applicationEnvironment$1.createJrtFileSystem(KotlinCoreEnvironment.kt:483)
        at org.jetbrains.kotlin.com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:107)
        at org.jetbrains.kotlin.com.intellij.core.JavaCoreApplicationEnvironment.<init>(JavaCoreApplicationEnvironment.java:63)
        at org.jetbrains.kotlin.com.intellij.core.JavaCoreApplicationEnvironment.<init>(JavaCoreApplicationEnvironment.java:59)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion$createApplicationEnvironment$applicationEnvironment$1.<init>(KotlinCoreEnvironment.kt:480)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createApplicationEnvironment(KotlinCoreEnvironment.kt:480)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.getOrCreateApplicationEnvironmentForProduction(KotlinCoreEnvironment.kt:457)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:409)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:240)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createEnvironmentWithScriptingSupport(K2JVMCompiler.kt:230)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
        at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.java:182)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.compileChanged(IncrementalJvmCompilerRunner.kt:443)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.compileIncrementally(IncrementalJvmCompilerRunner.kt:301)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.compile(IncrementalJvmCompilerRunner.kt:128)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.execIncrementalCompiler(CompileServiceImpl.kt:452)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$execIncrementalCompiler(CompileServiceImpl.kt:99)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$$special$$inlined$withIC$lambda$1.invoke(CompileServiceImpl.kt:379)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$$special$$inlined$withIC$lambda$1.invoke(CompileServiceImpl.kt:99)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2$$special$$inlined$withValidClientOrSessionProxy$lambda$1.invoke(CompileServiceImpl.kt:798)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2$$special$$inlined$withValidClientOrSessionProxy$lambda$1.invoke(CompileServiceImpl.kt:99)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:825)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$checkedCompile(CompileServiceImpl.kt:99)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2.invoke(CompileServiceImpl.kt:797)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$2.invoke(CompileServiceImpl.kt:99)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.ifAlive(CompileServiceImpl.kt:1004)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.ifAlive$default(CompileServiceImpl.kt:865)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:791)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$doCompile(CompileServiceImpl.kt:99)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1.invoke(CompileServiceImpl.kt:378)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1.invoke(CompileServiceImpl.kt:99)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.ifAlive(CompileServiceImpl.kt:1004)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.ifAlive$default(CompileServiceImpl.kt:865)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:336)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:374)
        at sun.rmi.transport.Transport$1.run(Transport.java:212)
        at sun.rmi.transport.Transport$1.run(Transport.java:209)
        at java.security.AccessController.doPrivileged(AccessController.java:686)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:208)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:580)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:838)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:695)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$8.00000000E4013540.run(Unknown Source)
        at java.security.AccessController.doPrivileged(AccessController.java:620)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:694)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:785)


> Task :buildSrc:compileKotlin
Using kotlin incremental compilation


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 4s
```
### Your Environment
RHEL 7.3x, IBM JDK 1.8.0.4.10
```
[vagrant@localhost build-scan]$ uname -a
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@localhost samples]$ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr4fp10-20170727_01(SR4 FP10))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20170722_357405 (JIT enabled, AOT enabled)
J9VM - R28_20170722_0201_B357405
JIT  - tr.r14.java_20170722_357405
GC   - R28_20170722_0201_B357405_CMPRSS
J9CL - 20170722_357405)
JCL - 20170726_01 based on Oracle jdk8u144-b01
[vagrant@localhost samples]$ javac -version
javac 1.8.0
[vagrant@localhost samples]$ which javac
/usr/bin/javac
[vagrant@localhost samples]$ ls -AlF /usr/bin/javac
lrwxrwxrwx. 1 root root 23 Aug 22 12:03 /usr/bin/javac -> /etc/alternatives/javac*
[vagrant@localhost samples]$ ls -AlF /etc/alternatives/javac
lrwxrwxrwx. 1 root root 66 Aug 22 12:03 /etc/alternatives/javac -> /usr/lib/jvm/java-1.8.0-ibm-1.8.0.4.10-1jpp.3.el7.x86_64/bin/javac*
```
This is a different (passing) build performed on the same machine

 * Build scan URL: https://scans.gradle.com/s/4aah3jowqqpp6

**Comment by bamboo** [comment] 2017-08-22 12:58
Thanks for the report, @jdanekrh.

**Comment by JLLeitschuh** [comment] 2017-08-30 18:08
We could test gradle script kotlin with IBM's J9 on Travis CI after this PR is merged:
https://github.com/travis-ci/travis-cookbooks/pull/874

**Comment by JLLeitschuh** [comment] 2017-08-31 14:58
Should this be captured in a Youtrack issue if this is a compiler bug?

**Comment by eskatos** [comment] 2017-08-31 15:02
From the details above this does not look related to the Gradle Kotlin DSL but to the Gradle Kotlin Plugin. IOW, it's the `compileKotlin` task that fails, not the compilation of build scripts.

Good call @JLLeitschuh

**Comment by eskatos** [comment] 2017-09-07 09:54
@JLLeitschuh did you end up creating a Youtrack issue? I can do it if you didn't already

**Comment by JLLeitschuh** [comment] 2017-09-07 13:52
I haven't yet. Sorry been busy. If you have the cycles please do open an issue.

**Comment by eskatos** [comment] 2017-09-12 11:44
After further investigation, I cannot reproduce at `v0.11.1`, `v0.10.3` nor from the `develop` branch.

```
paul@ubuntu-1704 $ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr4fp1-20170215_01(SR4 FP1))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20170209_336038 (JIT enabled, AOT enabled)
J9VM - R28_20170209_0201_B336038
JIT  - tr.r14.java.green_20170125_131456
GC   - R28_20170209_0201_B336038_CMPRSS
J9CL - 20170209_336038)
JCL - 20170215_01 based on Oracle jdk8u121-b13
```

@jdanekrh, could you confirm you can reproduce, either always or sporadically?

**Comment by bamboo** [comment] 2017-09-28 14:01
Closing for now. @jdanekrh, please re-open with more information if it happens again.

**Closed by bamboo** 2017-09-28 14:01 UTC
Labels: a:bug, in:kt-compiler, is:blocking

**Comment by jdanekrh** [comment] 2017-10-06 10:27
Works for me too, after I have updated Gradle to version 4.2 (I had 4,1 before).

I can reproduce the previous error with current master of kotlin-dsl (201534f53) if I downgrade Gradle to 4.1 with `./gradlew wrapper --gradle-version 4.1` first.
