### ISSUE TITLE
Generated `build-dashboard` link is incorrect

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#1019] opened 2018-08-08 16:17 UTC
The link generated for this accessor is incorrect:
```kotlin
/**
 * The builtin Gradle plugin implemented by [org.gradle.api.reporting.plugins.BuildDashboardPlugin].
 *
 * Visit the [plugin user guide](https://docs.gradle.org/current/userguide/buildDashboard_plugin.html) for additional information.
 *
 * @see org.gradle.api.reporting.plugins.BuildDashboardPlugin
 */
inline val PluginDependenciesSpec.`build-dashboard`: PluginDependencySpec
    get() = id("org.gradle.build-dashboard")
```
Instead, it should be this:
https://docs.gradle.org/current/userguide/build_dashboard_plugin.html

```
------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.13.5 x86_64
```

**Comment by eskatos** [comment] 2018-08-08 16:29
Already fixed, closing as duplicate of #835

**Closed by eskatos** 2018-08-08 16:29 UTC
Labels: was:duplicate
