### ISSUE TITLE
Embeded Kotlin version is used for Transitive dependencies for Kotlin libs 

### ISSUE THREAD

**Issue by redtankd** [gradle/kotlin-dsl#588] opened 2017-11-07 14:58 UTC
My grade's version is 4.3. This is my parent project:

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    val kotlinVersion = "1.2.0-rc-39"
    kotlin("jvm") version kotlinVersion apply false
    kotlin("plugin.spring") version kotlinVersion apply false

    id("io.spring.dependency-management") version "1.0.3.RELEASE"
    id("org.springframework.boot") version "2.0.0.M6" apply false // translated in settings.gradle
    id("org.junit.platform.gradle.plugin") version "1.0.0" apply false // translated in settings.gradle
}

subprojects {
    apply {
        plugin("io.spring.dependency-management")
        plugin("org.junit.platform.gradle.plugin")
    }

    group = "org.redtank.demo"
    version = "0.0.1-SNAPSHOT"

    tasks {
        withType<KotlinCompile> {
            kotlinOptions {
                jvmTarget = "1.8"
            }
        }
    }

    dependencyManagement {
        dependencies {
            imports {
                mavenBom("org.springframework.cloud:spring-cloud-dependencies:Finchley.M3")
                mavenBom("org.apache.curator:apache-curator:4.0.0")
            }

            dependency("org.javamoney:moneta:1.1")
            dependency("org.zalando:jackson-datatype-money:1.0.0-RC2")

            dependencySet("org.apache.ignite:2.3.0") {
                entry("ignite-core")
                entry("ignite-spring")
                entry("ignite-spring-data")
                entry("ignite-indexing")
            }

            dependency("org.apache.zookeeper:zookeeper:3.4.9") // for apache-curator
            dependency("log4j:log4j:1.2.17") // for io.spring.gradle.dependencymanagement
        }
    }

    repositories {
        jcenter()
        mavenCentral()
        maven(url = "https://repo.spring.io/milestone")
        maven(url = "https://repo.spring.io/snapshot")
        maven(url = "http://dl.bintray.com/kotlin/kotlin-eap-1.2")
    }
}
```

This is my child project:

```
plugins {
    kotlin("jvm")
    kotlin("plugin.spring")
    `application`
    id("org.springframework.boot")
}

application {
    mainClassName = "config.StandaloneGitServerApplicationKt"
}

dependencies {
    implementation(kotlin("stdlib-jre8"))
    implementation(kotlin("reflect"))

    implementation("org.springframework.cloud:spring-cloud-config-server")
    implementation("org.springframework.boot:spring-boot-starter-actuator")

    testImplementation("org.junit.jupiter:junit-jupiter-engine")
}
```

the `setting.gradle` is 

```
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if ("org.springframework.boot" == requested.id.toString()) {
                useModule("org.springframework.boot:spring-boot-gradle-plugin:${requested.version}")
            }
            if ("org.junit.platform.gradle.plugin" == requested.id.toString()) {
                useModule("org.junit.platform:junit-platform-gradle-plugin:${requested.version}")
            }
        }
    }
    repositories {
        gradlePluginPortal()
        maven { url "https://repo.maven.apache.org/maven2/" }
        maven { url "http://dl.bintray.com/kotlin/kotlin-eap-1.2" }
        maven { url "https://repo.spring.io/plugins-snapshot/" }
    }
}
```

The dependencies map is 

```
+--- org.jetbrains.kotlin:kotlin-stdlib-jre8: -> 1.2.0-rc-39
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.0-rc-39 -> 1.1.51
|    |    \--- org.jetbrains:annotations:13.0
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.0-rc-39 -> 1.1.51
|         \--- org.jetbrains.kotlin:kotlin-stdlib:1.1.51 (*)
+--- org.jetbrains.kotlin:kotlin-reflect: -> 1.2.0-rc-39
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.0-rc-39 -> 1.1.51 (*)
```

`org.jetbrains.kotlin:kotlin-stdlib` should not be 1.1.51.

**Comment by mkobit** [comment] 2017-11-07 15:02
This might be caused by the [Spring dependency-management-plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin), as I have frustratingly dealt with this behavior before.

**Comment by bamboo** [comment] 2017-11-08 13:33
Thanks for the report, @redtankd but it doesn't look like this issue is caused by the `kotlin-dsl` itself as can be demonstrated by the following build scripts:

```kotlin
// settings.gradle.kts pointing to the Kotlin's EAP repository
pluginManagement {
    repositories {
        maven { url = uri("https://dl.bintray.com/kotlin/kotlin-eap-1.2/") }
    }
}

// build.gradle.kts applying the Kotlin plugin rc
plugins {
    kotlin("jvm") version "1.2.0-rc-39"
}

dependencies {
    compile(kotlin("stdlib"))
}

repositories {
    maven(url = "https://dl.bintray.com/kotlin/kotlin-eap-1.2/")
    jcenter()
}
```

Running `./gradlew dependencies` outputs the expected version of `stdlib`:

```
➜   ./gradlew dependencies --configuration compile -q

------------------------------------------------------------
Root project
------------------------------------------------------------

compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
\--- org.jetbrains.kotlin:kotlin-stdlib: -> 1.2.0-rc-39
     \--- org.jetbrains:annotations:13.0

```

I suspect some plugin might be getting confused by the presence of the `1.1.51` version of the `stdlib` in the build environment (the environment where the build script itself is evaluated):

```
➜  ./gradlew buildEnv -q

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
\--- org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.2.0-rc-39
     \--- org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.0-rc-39
          +--- org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.2.0-rc-39
          |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.0-rc-39 -> 1.1.51
          +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.0-rc-39 -> 1.1.51
          +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.2.0-rc-39
          |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.0-rc-39 -> 1.1.51
          |    +--- org.jetbrains.kotlin:kotlin-script-runtime:1.2.0-rc-39
          |    \--- org.jetbrains.kotlin:kotlin-reflect:1.2.0-rc-39 -> 1.1.51
          +--- org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.2.0-rc-39
          |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.0-rc-39 -> 1.1.51
          |    \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.2.0-rc-39 (*)
          +--- org.jetbrains.kotlin:kotlin-android-extensions:1.2.0-rc-39
          |    \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.2.0-rc-39 (*)
          \--- org.jetbrains.kotlin:kotlin-compiler-runner:1.2.0-rc-39
               +--- org.jetbrains.kotlin:kotlin-build-common:1.2.0-rc-39
               +--- org.jetbrains.kotlin:kotlin-daemon-client:1.2.0-rc-39
               \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.2.0-rc-39 (*)

(*) - dependencies omitted (listed previously)
```

I hope that helps.

I'm closing the issue for now but If you find a small repro we would be happy to take a look.

**Closed by bamboo** 2017-11-08 13:33 UTC

**Comment by redtankd** [comment] 2017-12-08 02:37
@bamboo 

I got it. It is caused by Spring Boot's gradle plugin , which imports dependencies on kotlin.
