### ISSUE TITLE
Automatically generated accessors for sourceSets not applied to kotlin-dsl-precompiled-script-plugins

### ISSUE THREAD

**Issue by sic-bre** [gradle/kotlin-dsl#1226] opened 2018-10-31 23:00 UTC
When using a kotlin-dsl-precompiled-script-plugins the automatically generated accessor for sourceSets that is applied to a regular build.gradle.kts file is not applied.  Manually inserting the accessors that should have been visible works. 

### Expected Behavior
All the accessors that appear in a build.gradle.kts should be available in kotlin-dsl-precompiled-script-plugins files.

### Current Behavior
Currently the accessor for sourceSets is not available in gradle-5.0-rc-1.

### Context
This was discovered when trying to port builds from gradle-10.2 to gradle-5.0-rc-1 using the kotlin-dsl-precompiled-script-plugins feature.

### Steps to Reproduce (for bugs)
Using gradle-5.0-rc-1 create a simple project with an empty settings.gradle.kts file, and this in the build.gradle.kts and note that the sourceSets is visible at this level:

```
plugins {
    `java-gradle-plugin`
    `kotlin-dsl`
    `kotlin-dsl-precompiled-script-plugins`
}

sourceSets
```

Then add in src/main/kotlin/test.gradle.kts:
```
sourceSets
```

References to the sourcesSets in the src/main/kotlin/test.gradle.kts will not work.  But if you manually add the accessors to src/main/kotlin/test.gradle.kts:

```
val org.gradle.api.Project.`sourceSets`: org.gradle.api.tasks.SourceSetContainer get() =
    (this as org.gradle.api.plugins.ExtensionAware).extensions.getByName("sourceSets") as org.gradle.api.tasks.SourceSetContainer
fun org.gradle.api.Project.`sourceSets`(configure: org.gradle.api.tasks.SourceSetContainer.() -> Unit): Unit =
    (this as org.gradle.api.plugins.ExtensionAware).extensions.configure("sourceSets", configure)
```

### Your Environment
Windows and linux command line builds on gradle-5.0-rc-1 with our without using Intellij 2018.2.5 fully patched.

 * Build scan URL:  NA

**Comment by bamboo** [comment] 2018-11-01 11:09
Thanks, @sic-bre. That's #673.

**Comment by eskatos** [comment] 2018-11-06 16:14
Closing as a duplicate of #673

**Closed by eskatos** 2018-11-06 16:14 UTC
Labels: a:feature, in:kotlin-dsl-plugins, is:blocked, re:ease-of-use, re:plugin-support
