### ISSUE TITLE
Gradle dependencies resolution failing when run through Idea

### ISSUE THREAD

**Issue by NikolayMetchev** [gradle/kotlin-dsl#1230] opened 2018-11-02 13:28 UTC
Jetbrains has asked me to file this bug here. Original bug was filed against Idea:
https://youtrack.jetbrains.com/issue/KT-27917

Gradle is throwing an exception which can be seen in the attached resolver log file. This exception doesn't occur when I run Gradle from the command line.

We are using Gradle 4.10.2 
IntelliJ IDEA 2018.3 EAP (Ultimate Edition)
Build #IU-183.4139.22, built on October 31, 2018
IntelliJ IDEA EAP User
Expiration date: November 30, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

[build.gradle.kts.zip](https://github.com/gradle/kotlin-dsl/files/2542582/build.gradle.kts.zip)
[resolver-2018-11-02-09-53-59-794.log](https://github.com/gradle/kotlin-dsl/files/2542583/resolver-2018-11-02-09-53-59-794.log)
![image](https://user-images.githubusercontent.com/417373/47917988-22390d80-dea3-11e8-8792-4892847380eb.png)

**Comment by eskatos** [comment] 2018-11-05 08:37
Thanks for the report @NikolayMetchev 
Could you try with Gradle 5.0-rc-1?

**Comment by NikolayMetchev** [comment] 2018-11-05 10:17
Doesn't appear to have helped with this problem.
[resolver-2018-11-05-10-14-44-104.log](https://github.com/gradle/kotlin-dsl/files/2547921/resolver-2018-11-05-10-14-44-104.log)

**Comment by eskatos** [comment] 2018-11-05 10:24
Thanks for trying. I can't reproduce by putting the single script provided in the report into a directory, and importing that directory as a Gradle build in IJ, it simply fails to import because the build isn't complete. Could you provide a build that reproduce the issue?

**Comment by NikolayMetchev** [comment] 2018-11-05 11:13
I tried to recreate it. I am getting the same symptoms but different error with the attached project.
[gradle idea bug.zip](https://github.com/gradle/kotlin-dsl/files/2548121/gradle.idea.bug.zip)

**Comment by eskatos** [comment] 2018-11-05 11:37
Thanks for the reproducer, I can reproduce with any Gradle Kotlin DSL version.

What happens is that given the layout of your build where one subproject build script is outside the build root dir, the script dependencies resolver consider it as a script plugin, not as a project build script, and thus provide wrong dependencies to the IDE editor.

**Comment by NikolayMetchev** [comment] 2018-11-05 11:41
OK. Is this an IDEA bug or a kotlin-gradle-dsl bug?

**Comment by eskatos** [comment] 2018-11-05 11:42
it's a `gradle/kotlin-dsl` bug, this issue is in the right place!

**Comment by eskatos** [comment] 2018-11-06 15:51
Closing in favor of #1231

**Closed by eskatos** 2018-11-06 15:51 UTC
Labels: a:bug, in:kotlin-dsl-ij-resolver, is:blocked
