### ISSUE TITLE
build.gradle.kts all RED in latest IntelliJ 2017.2 EAP

### ISSUE THREAD

**Issue by xmlking** [gradle/kotlin-dsl#368] opened 2017-05-19 00:28 UTC
How to reproduce :
https://github.com/xmlking/reactive-apps 

![image](https://cloud.githubusercontent.com/assets/627951/26228518/40962be4-3bef-11e7-85d3-5d786e15a545.png)

**Comment by akofke** [comment] 2017-06-16 15:29
This is happening for me as well, I'd be very interested in how to fix it.

**Comment by xmlking** [comment] 2017-06-16 16:54
After upgrading to latest EAP IntelliJ and gradle 4, don't see this issue

**Comment by CarsonF** [comment] 2017-06-16 22:42
Same for me on Gradle 4.0 and 2017.2 EAP 172.2953.9. However, if I open the project with 2017.1.4, and then go back to the EAP it works fine.

Digging further it looks like the EAP isn't automatically setting up / linking the gradle project, but 2017.1.4 does.

**Comment by crummy** [comment] 2017-08-11 10:23
I see this behaviour on 2017.2.2 EAP.

**Comment by hanct** [comment] 2017-10-13 13:10
I see this behaviour on 2017.2.5, so any solution

**Comment by eskatos** [comment] 2017-10-13 13:22
I just tried opening the reproducer project (https://github.com/xmlking/reactive-apps) in IntelliJ 2017.2.5 with the Kotlin Plugin 1.1.51. I did not run the build from the command line before that, so importing took time downloading all the dependencies.

Once IntelliJ had finished importing the project I opened the root `build.gradle.kts` file. It was all red at first display, then IntelliJ started resolving the script dependencies, once done (<1s), everything looked normal:

![image](https://user-images.githubusercontent.com/132773/31548087-0226c760-b02a-11e7-990e-a494285ead53.png)

@xmlking, @akofke, @CarsonF, @crummy, @hanct, can any of you reproduce the issue and share build/steps?

**Comment by xmlking** [comment] 2017-10-13 14:26
They are working fine now. Also tested with latest gradle 4.2.1 in project @ https://github.com/xmlking/microservices-observability and no issues with IntelliJ 
We can close the ticket.

**Comment by hanct** [comment] 2017-10-13 15:06
eskatos: it works.

**Comment by eskatos** [comment] 2017-10-13 15:07
Thank you @xmlking & @hanct!

Closing

**Closed by eskatos** 2017-10-13 15:07 UTC
Labels: a:bug

**Comment by hanct** [comment] 2017-10-13 15:09
I dont understand. My own project folder contains build.gradle.kts, and its content is only few lines as shown below, and yet there are red lines all over the place

(note: me using intellij 2017.2.5, and using my own local gradle distribution 2.5.1)

plugins {
    java
}

application {
    mainClassName = "ro.jtonic.tests.gradlekt.MyClass"
}

**Comment by JLLeitschuh** [comment] 2017-10-13 15:12
> gradle distribution 2.5.1

That is way too old.
You need at least Gradle 3.5 I think to have any grade script kotlin support.

You should try and use Gradle 4.2 to get these features.

**Comment by hanct** [comment] 2017-10-13 15:13
Sorry, typo error. Should be Gradle 4.2.1

**Comment by JLLeitschuh** [comment] 2017-10-13 15:15
Try Invalidating caches and restarting IntelliJ.

If that doesn't work go to `Help > Show Logs In Finder` and see if there are any useful errors in your IntelliJ logs.

Sometimes I have to restart IntelliJ for everything to work. Especially after gradle updates.

**Comment by hanct** [comment] 2017-10-13 17:39
Hi,

I try invalidate cache, restart Intellij, recreate new project, etc.... (try for few days already), I still get red lines in the build.gradle.kts. 
Below I show a screenshot, to show the error and configuration.


![image](https://user-images.githubusercontent.com/4410920/31558593-2888d636-b080-11e7-96e0-ef0f9283f8eb.png)

**Comment by wemu** [comment] 2017-10-13 18:01
I sometimes have similar effects when opening gradle builds in Intellij. But for both .gradle and .kts build files. So I assume its more on the Intellij side. Sometimes these red markers go away and Intellij does recognize its not only groovy or kotlin but a gradle file. Haven't found out yet what prevents this. It only ever worked with later gradle 4.2 RCs.

Sometimes executing a few tasks on the command line via the wrapper makes it go away. Invalidating the caches wont do this every time. When starting from scratch... well - maybe adding the java plugin and then just ./gradlew build once?

**Comment by hanct** [comment] 2017-10-14 06:52
ok. Thanks. I think i manage to resolve the red color error in my build.gradle.kts. Finally!
What i mainly do is invalidate cache and delete away the .gradle folder in my user folder and boom! the error gone.  I think the latter action (delete away the .gradle folder) could be the one resolving the issue

Thanks everyone for your great help!!!

**Comment by visakha** [comment] 2017-12-16 23:48
Using 
IntelliJ IDEA 2017.3.1 (Ultimate Edition)
Build #IU-173.3942.27, built on December 11, 2017


I hit the same issue
re-start of the IDE and then build->Rebuild Project fixed the issue

**Comment by Dollyn** [comment] 2018-03-28 13:38
I tried  remove .gradle under home dir, .gradle under project dir, invalidate cache and restart, rebuild project ... and still got lots of errors, 

build info:
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 27, 2018
Licensed to dollyn sun
Subscription is active until March 21, 2019
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

idea.log
[idea.log](https://github.com/gradle/kotlin-dsl/files/1856163/idea.log)
