### ISSUE TITLE
kotlin-dsl-precompiled-script-plugins nested in packages are not found

### ISSUE THREAD

**Issue by sic-bre** [gradle/kotlin-dsl#1227] opened 2018-11-01 04:16 UTC
When creating a kotlin-dsl-precompiled-script-plugins nested in a package it is not loaded by gradle-5.0-rc-1 even though the generated plugin appears to be properly formatted. 

### Expected Behavior
I should be able to create a kotlin-dsl-precompiled-script-plugins nested in a package or at the top level and it should work correctly.

### Current Behavior
Top level kotlin-dsl-precompiled-script-plugins are built and found but those nested in packages are not found.

### Context
When porting kotlin-dsl-precompiled-script-plugins to gradle-5.0-rc-1 I discovered that nested packages are not found.

### Steps to Reproduce (for bugs)
Expand the [test.zip](https://github.com/gradle/kotlin-dsl/files/2537189/test.zip)
Change to the test directory
With gradle-5.0-rc1 run `gradle nonnested` task
Edit the top level build.gradle.kts and uncomment the "plugins { //\`nested.nested\` }"
With gradle-5.0-rc1 run `gradle nested` task
Observer the nested.nested plugin is not located:

```
PS C:\Users\s002681\test> gradle nested

> Configure project :
e: C:\Users\s002681\test\build.gradle.kts:4:2: Unresolved reference: `nested.nested`

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\s002681\test\build.gradle.kts' line: 4

* What went wrong:
Script compilation error:

  Line 4:       `nested.nested`
           ^ Unresolved reference: `nested.nested`

1 error
```

### Your Environment
Command line gradle-5.0-rc-1

**Comment by bamboo** [comment] 2018-11-01 11:33
Hi, @sic-bre. Does the precompiled script plugin include the correct `package` declaration?

Please note the plugin id for a precompiled script plugin is `<declared package name>.<file name minus the .gradle.kts suffix>` as [this test case](https://github.com/gradle/kotlin-dsl/blob/611912e7e073b2171f479212a3cfa31e10217241/subprojects/plugins/src/test/kotlin/org/gradle/kotlin/dsl/plugins/precompiled/PrecompiledScriptPluginTest.kt#L180) demonstrates.

The Gradle build provides many examples as well, see for instance how the [`gradlebuild.script-compile` precompiled script plugin](https://github.com/gradle/gradle/blob/7cda3aac7c425a8525233ee804d58d9d87f3debe/buildSrc/subprojects/plugins/src/main/kotlin/gradlebuild/strict-compile.gradle.kts#L16-L15) is defined and then [used](https://github.com/gradle/gradle/blob/0bc46b683cff3f4700544a548a1a9c8746ee3ddb/subprojects/tooling-native/tooling-native.gradle.kts#L4).

**Comment by sic-bre** [comment] 2018-11-01 13:50
Yes it includes a package declaration and the generated.  The generated buildSrc.jar:META-INF/gradle-plugins/nested.nested.properties contains: `implementation-class=nested.NestedPlugin` as expected.

You may have missed my link above to a downloadable sample that demonstrates the behavior (here it is again: [test.zip](https://github.com/gradle/kotlin-dsl/files/2537189/test.zip)) that has all the files I tested.  The file src/main/kotlin/nested/nested.gradle.kts contains:

```
package nested

val nested by tasks.registering(DefaultTask::class) {
    doLast {
        println("nested")
    }
}
```

**Comment by bamboo** [comment] 2018-11-01 14:16
It seems the problem is in the use of backticks around the fully qualified plugin name. Backticks are for [escaping a single identifier](https://kotlinlang.org/docs/reference/java-interop.html#escaping-for-java-identifiers-that-are-keywords-in-kotlin) and that ends up escaping the dot inside the fully qualified name. You don't want that because the Kotlin DSL provides hierarchical plugin ids via regular namespaced Kotlin extensions.

Try it without the backticks.

**Comment by eskatos** [comment] 2018-11-05 09:02
@sic-bre, note that you can navigate from the plugin spec declaration to the plugin implementation.

Closing as it works as intended.

**Closed by eskatos** 2018-11-05 09:02 UTC

**Comment by sic-bre** [comment] 2018-11-05 16:02
Maybe I'm missing something but I can't figure out how to get Intellij to do that navigation to plugins created in the buildSrc project:

Ctrl-B take me to the generated PluginAccessors.kt which has lines that look like this for my buildSrc declared plugins:

```
/**
 * The `buildsrc-tasks` plugin implemented by [BuildsrcTasksPlugin].
 */
val `PluginDependenciesSpec`.`buildsrc-tasks`: PluginDependencySpec
    get() = this.id("buildsrc-tasks")
```

And if I Ctrl-B on the BuildsrcTasksPlugin it gives me an error message "Cannot find declaration to go to."

```
/**
 * The `kotlin` plugin implemented by [org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapper].
 */
val `PluginDependenciesSpec`.`kotlin`: PluginDependencySpec
    get() = this.id("kotlin")
```

Note if I choose one of the builtin plugins the navigation to `org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapper` does work so it seems to be something specific to how the buildSrc plugins are being processed.

**Comment by eskatos** [comment] 2018-11-05 16:11
It's specific to the default package, see #1205
