### ISSUE TITLE
build.gradle.kts Syntax Highlighting not working in Intellij IDEA

### ISSUE THREAD

**Issue by Xerus2000** [gradle/kotlin-dsl#691] opened 2018-01-23 19:43 UTC
Most of the time, when I open a build.gradle.kts file, Intellij does not recognise anything in it, which deters me from using kotlin-dsl, as much as I am fond of Kotlin...

### Expected Behavior
build.gradle.kts should have syntax highlighting

### Current Behavior
Everything is red saying "Unresolved reference" on hover
![image](https://user-images.githubusercontent.com/13354331/35297022-08278088-007e-11e8-82cc-e406c25a93ef.png)

### Context
I want to start using kotlin instead of groovy for my buildscript, but if syntax highlighting doesn't work this move would be useless

### Steps to Reproduce (for bugs)
1. `git clone https://github.com/gradle/kotlin-dsl ~/kotlin-dsl`
2. In IDEA, go to `File->Open...` and navigate to `~/kotlin-dsl/samples/hello-world`
3. Import the project using all the default settings
4. Open build.gradle.kts

### Your Environment
Intellij IDEA 2017.3.3
Kotlin Plugin Version: 1.2.20-release-IJ2017.3-1

**Comment by Xerus2000** [comment] 2018-01-23 20:04
apparently it works now after invalidating caches, restarting and waiting a bit. But that is too unreliable...

**Comment by JLLeitschuh** [comment] 2018-01-23 20:26
I find that when I have a lot of Gradle Kotlin DSL files in a project, when I open one up I want to edit, I often have to use the "Refresh" button in the "Gradle projects" tab on the right side of IntelliJ before the syntax highlighting works.

If it's still not working after you do that check the IntelliJ logs: `Help -> Show Log in Finder` or your OS equivalent.
There might be an exception in there that IntelliJ is getting trying to add highlighting to the AST.

**Comment by eskatos** [comment] 2018-01-24 08:06
Closing as a duplicate of #608 
Please upvote the upstream issue linked in #608!

**Closed by eskatos** 2018-01-24 08:06 UTC
Labels: was:duplicate
