### ISSUE TITLE
enabled = false for a take not working from 4.2-RC-1

### ISSUE THREAD

**Issue by xmlking** [gradle/kotlin-dsl#488] opened 2017-09-09 20:02 UTC
I have gradle multi-project where one of the subproject is  `shared` project which all other subprojects depends on. i.e., `compile(project(":shared"))`
I am disabling  `BootJar` task by setting ` enabled = false`. This was working in previous Gradle versions but not working after upgrading to  4.2-RC-1
`BootJar` in `shared` project still get executed when I run `gradle build` at multi-project root level.

**example project to reproduce this issue** : https://github.com/xmlking/reactive-apps
 > previous issue reference : https://github.com/gradle/kotlin-dsl/issues/393

**shared subproject build.gradle.kts**
```kotlin
import org.gradle.api.tasks.bundling.Jar
import org.springframework.boot.gradle.tasks.bundling.BootJar

// Prevents common subproject dependencies from being included in the common jar itself.
// Without this, each subproject that included common would include each shared dependency twice.
tasks {
    withType<BootJar> {
        enabled = false
        classifier = "boot"
        mainClass = "some.dummy.class"
    }
    withType<Jar> {
        enabled = true
    }
}
```

**Comment by xmlking** [comment] 2017-09-10 15:53
After changing the above code to this format, it worked as expected. shoud above syntax also work? is it a bug?
```
import org.gradle.api.tasks.bundling.Jar
import org.springframework.boot.gradle.tasks.bundling.BootJar

// Prevents common subproject dependencies from being included in the common jar itself.
// Without this, each subproject that included common would include each shared dependency twice.
val jar: Jar by tasks
val bootJar: BootJar by tasks

bootJar.enabled = false
jar.enabled = true
```

**Comment by eskatos** [comment] 2017-09-12 10:20
Thanks for the report @xmlking 
I can reproduce in your project.

Build scans for `build -x test` from a clean working copy:
- [before the workaround](https://scans.gradle.com/s/p25bnnzllnhji/timeline?task=k6qbhq6odljey&taskFilter=bootJar)
- [with the workaround](https://scans.gradle.com/s/eisb5zxz4o7hq/timeline?task=k6qbhq6odljey&taskFilter=bootJar)

**Comment by eskatos** [comment] 2017-09-12 10:38
I can also reproduce with either:
- Gradle 4.1 - [using `withType`](https://scans.gradle.com/s/yu3ag4zriw72s/timeline?task=k6qbhq6odljey&taskFilter=bootJar) - [direct task access](https://scans.gradle.com/s/nt4h4iifivirs/timeline?task=k6qbhq6odljey&taskFilter=bootJar)
- a Groovy build script in `:shared` - [using `withType`](https://scans.gradle.com/s/empups2va6fn6/timeline?task=k6qbhq6odljey&taskFilter=bootJar) - [direct task access](https://scans.gradle.com/s/lbup5zepnaytg/timeline?task=k6qbhq6odljey&taskFilter=bootJar)

I'd say it's a Gradle issue, not a Kotlin DSL one.
@xmlking could you please report to [gradle/gradle](https://github.com/gradle/gradle/issues/new) instead?

**Comment by eskatos** [comment] 2018-01-18 09:31
Closing in favor of upstream https://github.com/gradle/gradle/issues/4073

**Closed by eskatos** 2018-01-18 09:31 UTC

**Comment by eskatos** [comment] 2018-01-18 09:55
@xmlking, it turns out this is the expected behavior.

Quoting @oehme:
> BootJar extends Jar, so the second withType statement reactivates it. This is just expected behavior.
>
> Accessing by name makes more sense here, since the user doesn't actually want to "activate all tasks that extend JAR", but "activate the jar task".
