### ISSUE TITLE
Cannot build sample hello-world with settings.gradle.kts but builds by adding settings.gradle

### ISSUE THREAD

**Issue by vashisthg** [gradle/kotlin-dsl#651] opened 2018-01-06 16:31 UTC
I tried to follow the instructions in README but intellij did not build the project correctly similar to https://github.com/gradle/kotlin-dsl/issues/643. However I could build the project through terminal `./gradlew build`

However when I added a file `settings.gradle` and then imported the project. It worked. 

### Expected Behavior
Project should build in intellij with settings.gradle.kts

### Current Behavior
- Project did not build when I opened the project as per README [`File->Open`](https://github.com/gradle/kotlin-dsl/tree/master/samples#import-the-sample-project-into-idea)
<img width="796" alt="screen shot 2018-01-06 at 5 19 10 pm" src="https://user-images.githubusercontent.com/1661780/34641583-9a795324-f306-11e7-9f14-da6a418ceed9.png">

- Cannot import project with settings.gradle
<img width="606" alt="screen shot 2018-01-06 at 5 18 25 pm" src="https://user-images.githubusercontent.com/1661780/34641571-72aecebe-f306-11e7-975a-b25a1e767df0.png">

### Context

I am trying to run the sample project 'hello-world'. 
Sample project did not build as per the instructions

However sample project run when I add settings.gradle and import it. 
<img width="841" alt="screen shot 2018-01-06 at 5 17 39 pm" src="https://user-images.githubusercontent.com/1661780/34641592-ba663846-f306-11e7-9afe-7e51e91b5c77.png">

### Steps to Reproduce (for bugs)
Follow the instructions in https://github.com/gradle/kotlin-dsl/tree/master/samples#import-the-sample-project-into-idea

### Your Environment
- Macos Sierra 10.12.6
- Intellij Idea Community 2017.2.6

EDIT
Some more info on environment 
- Kotlin plugin Version: 1.2.10-release-IJ2017.2-1

**Comment by iNoles** [comment] 2018-01-06 20:26
What is your Kotlin version?

**Comment by vashisthg** [comment] 2018-01-06 20:58
@iNoles kotline version 1.2

**Comment by eskatos** [comment] 2018-01-10 12:09
@vashisthg what is the version of the Kotlin plugin you have installed in IntelliJ?

**Comment by vashisthg** [comment] 2018-01-10 13:03
@eskatos Kotlin plugin Version: 1.2.10-release-IJ2017.2-1

**Comment by eskatos** [comment] 2018-01-24 10:53
I can't reproduce with IntelliJ 2017.3.3 and Kotlin IntelliJ Plugin 1.2.20. I tried to point at the build root dir or at the `settings.gradle.kts` file when importing the project and IntelliJ did the right thing in both cases.

@vashisthg, can you reproduce on your side? Please also keep #608 in mind.

**Comment by eskatos** [comment] 2018-01-30 14:43
Closing as it is not reproducible and we got no more feedback

**Closed by eskatos** 2018-01-30 14:43 UTC
Labels: a:bug, by:jetbrains, in:kt-idea-plugin, re:editing, was:invalid
