### ISSUE TITLE
settings.gradle.kts syntax highlighting bugs in IDEA

### ISSUE THREAD

**Issue by gildor** [gradle/kotlin-dsl#658] opened 2018-01-15 09:08 UTC
settings.gradle.kts syntax highlighting doesn't work properly in Intellij IDEA.

### Expected Behavior
settings.gradle.kts should have syntax highlighting and navigation to a declaration in Intellij Idea

### Current Behavior
If you create settings.gradle.kts:
```
rootProject.name = 'projectName'
include(":some-project")
buildscript {
    repositories {
       jcenter()
    }
}
```

In Idea you will see that you have 2 errors in the file:
- "Val cannot be reassigned" for rootProject.name
- `include` is highlighted red and not resolved

But `buildscript` and nested DSLs works fine.

Also, this is completely IDE bug, build and configuration works with such settings.gradle.kts

### Context
I have this issue all the time now with all my project. I'm not sure, but probably this worked for me previously.

### Your Environment
IntelliJ IDEA 2017.3.2 (Ultimate Edition)
Build #IU-173.4127.27, built on December 26, 2017
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

**Comment by soberich** [comment] 2018-01-16 13:29
IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.14, built on January 9, 2018

everything looks great in settings.gradle.kts

**Comment by eskatos** [comment] 2018-01-24 09:20
Closing as a duplicate of #685

**Closed by eskatos** 2018-01-24 09:20 UTC
Labels: a:bug, in:kt-idea-plugin, re:editing, was:duplicate
