### ISSUE TITLE
Investigate build cache misses for stage 2 script compilation on `gradle/kotlin-dsl`

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#1123] opened 2018-09-18 14:43 UTC
From local machine consuming remote cache populated from CI:

stage 1 -> cache hit
stage 2 -> cache miss

The only difference between stage 1 and stage 2 cache keys is that the latter may include the accessors classpath.

We should check what the inputs to the `KotlinCompile` task are (os/arch/jvm etc..).

**Comment by bamboo** [comment] 2018-10-29 13:13
Script caching works as expected for `gradle/gradle` so it must be something about the CI setup of `gradle/kotlin-dsl`.

**Comment by bamboo** [comment] 2018-12-10 11:24
The cache misses were caused by different line endings in the generated source code that goes into the Kotlin DSL jars. 

Fixed by #1288.

**Closed by bamboo** 2018-12-10 11:24 UTC
Labels: a:bug, in:kotlin-dsl-runtime, re:performance
