### ISSUE TITLE
IDEA reports an error in buildSrc while Gradle compiles successfully

### ISSUE THREAD

**Issue by orange-buffalo** [gradle/kotlin-dsl#583] opened 2017-11-01 14:25 UTC
Consider the [simple project](https://github.com/gradle/kotlin-dsl/files/1434389/kotlin-dsl-buildsrc.zip) in attachment. It is a kotlin-dsl Gradle project with custom plugin defined in `buildSrc` directory. 

The plugin is calling `org.gradle.api.artifacts.dsl.ArtifactHandler#add(java.lang.String, java.lang.Object, org.gradle.api.Action<? super org.gradle.api.artifacts.ConfigurablePublishArtifact>)` method:
```kotlin
    project.artifacts.add("custom", project.provider({ artifactTask.archivePath })) {
        classifier = "custom"
    }
``` 

### Expected Behavior
IDEA should provide autocomplition inside the lambda expression and should visualize lambda expression as valid.  

### Current Behavior
IDEA highlights `classifier` in lambda expression with `Unresolved reference` error. Code completion is not working inside the lambda expression. 

### Steps to Reproduce (for bugs)
To compile the project with Gradle, run 
```
./gradlew clean artifactTask
```
This will be successful.

When project is imported in IDEA, the problematic behaviour can be observed.  

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/5iq5ucwba2v6m/
 * IDEA Kotlin plugin `1.1.51-release-IJ2017.2-1`
 * IDEA `2017.2.5`

**Comment by eskatos** [comment] 2017-11-02 09:35
Thanks for the report @orange-buffalo 
This is a duplicate of #476, closing

**Closed by eskatos** 2017-11-02 09:35 UTC

**Comment by orange-buffalo** [comment] 2017-11-02 09:47
Thanks for the update @eskatos, and sorry for the duplicate.
