### ISSUE TITLE
`WriteProperties#property(String, Object)` method of the task  should handle Kotlin lambda

### ISSUE THREAD

**Issue by lacasseio** [gradle/kotlin-dsl#1159] opened 2018-10-02 14:58 UTC
### Expected Behavior

Something like the following should write the result of the Kotlin lambda as the value for the property:
```
val pluginsManifest by tasks.registering(WriteProperties::class) {
    property("plugins") {
        pluginProjects.map { it.base.archivesBaseName }.sorted().joinToString(",")
    }
    outputFile = File(generatedResourcesDir, "gradle-plugins.properties")
}
```

### Current Behavior

Instead, the `WriteProperties` task expect a `Callable` which the Kotlin lambda is not and will simply cast the lambda to a String, aka `() -> String` or something similar. To work around the issue, you have to explicitly declare a `Callable` like the following:
```
val pluginsManifest by tasks.registering(WriteProperties::class) {
    property("plugins", Callable<String> {
        pluginProjects.map { it.base.archivesBaseName }.sorted().joinToString(",")
    })
    outputFile = File(generatedResourcesDir, "gradle-plugins.properties")
}
```

### Your Environment

 * Build scan URL:

**Comment by bamboo** [comment] 2018-10-02 15:00
Related work is currently in flight as part of #1077.

**Comment by eskatos** [comment] 2018-11-06 16:42
Closing as a duplicate of #1077

**Closed by eskatos** 2018-11-06 16:42 UTC
Labels: a:feature, in:gradle-api, re:dogfood
