### ISSUE TITLE
`project(String)` method in gradle dsl should have `@Nonnull` or similar

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#420] opened 2017-07-13 20:23 UTC
Since updating to the newest version of the the IntelliJ Kotlin plugin has added some warnings to my IDE that weren't there before.

Methods like this are now underlined with a yellow warning.
```kotlin
val applicationProject = project(":Application")
```
<img width="1010" alt="screen shot 2017-07-13 at 4 15 56 pm" src="https://user-images.githubusercontent.com/1323708/28185958-61d4d82c-67e7-11e7-93cc-143b4f401158.png">

Does the Gradle API need to be updated to add `@Nonnull` on methods that throw exceptions if they don't resolve themselves?

Gradle version: `4.0.1`
Kotlin Plugin Version: `1.1.4-eap-11-IJ2017.1-1`

```
IntelliJ IDEA 2017.1.5
Build #IU-171.4694.70, built on July 4, 2017
Licensed to Plexxi, Inc. / Jonathan Leitschuh
Subscription is active until December 14, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5
```

**Comment by bamboo** [comment] 2017-07-14 12:36
Unfortunately, the presence of either `javax.annotation.Nonnull` or `javax.annotation.Nullable` doesn't seem to have any effect on the warnings.

**Comment by bamboo** [comment] 2017-07-14 12:53
That's odd because according to the [reference docs](https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations) `javax.annotation.{Nullable, Nonnull}` are supported.

**Comment by JLLeitschuh** [comment] 2017-07-14 14:06
Does this mean that there is a bug in the IntelliJ Kotlin plugin?

**Comment by bamboo** [comment] 2017-07-18 20:49
@JLLeitschuh the plugin is good. The problem seems to be caused by the `javax.annotation` types not being exposed as part of the Gradle API jar.

**Comment by wolfs** [comment] 2017-07-19 08:41
This should be fixed via https://github.com/gradle/gradle/commit/3a59865d436691fc1bbf71885b39eb347fabd2cc.

**Closed** 2017-08-24 11:14 UTC
Labels: a:feature, in:gradle-api, re:ease-of-use, re:editing, re:toolability
