### ISSUE TITLE
gradle --version should print Kotlin compiler details

### ISSUE THREAD

**Issue by eriwen** [gradle/kotlin-dsl#729] opened 2018-02-22 23:38 UTC
It would be helpful to print Kotlin compiler version as part of `gradle --version`. 

### Expected Behavior
```
> gradle --version

------------------------------------------------------------
Gradle 4.5.1
------------------------------------------------------------

Build time:   2018-02-05 13:22:49 UTC
Revision:     37007e1c012001ff09973e0bd095139239ecd3b3

Groovy:       2.4.12
Kotlin:       1.2.21
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Mac OS X 10.13.3 x86_64
```

### Current Behavior
```
> gradle --version

------------------------------------------------------------
Gradle 4.5.1
------------------------------------------------------------

Build time:   2018-02-05 13:22:49 UTC
Revision:     37007e1c012001ff09973e0bd095139239ecd3b3

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Mac OS X 10.13.3 x86_64
```

### Context
This is one way to inform users about version of Kotlin compiler used to compile build scripts.

**Comment by bamboo** [comment] 2018-02-22 23:43
Closing as duplicate of #481.

**Closed by bamboo** 2018-02-22 23:43 UTC

**Comment by eriwen** [comment] 2018-02-22 23:45
D'oh. I had looked and didn't see that issue. Thanks!
