### ISSUE TITLE
Evaluation Dependency on a child project causes exception org.gradle.api.internal.initialization.DefaultClassLoaderScope@31920b27 must be locked before it can be used to compute a classpath!

### ISSUE THREAD

**Issue by NikolayMetchev** [gradle/kotlin-dsl#607] opened 2017-11-23 11:53 UTC
Attached is a project that cannot be built but I am not sure exactly why it is breaking. A dependency on a child project (e.g. :parent:b) breaks gradle kotlin dsl.

### Expected Behavior
project to build

### Current Behavior
output of gradlew clean command:
* What went wrong:
A problem occurred configuring project ':a'.
> A problem occurred configuring project ':parent:b'.
   > org.gradle.api.internal.initialization.DefaultClassLoaderScope@31920b27 must be locked before it can be used to compute a classpath!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

### Steps to Reproduce (for bugs)
[dependencyEvaluationBug.zip](https://github.com/gradle/kotlin-dsl/files/1498897/dependencyEvaluationBug.zip)
Attached is a zip file that can be used to reproduce the issue

### Your Environment
Windows 10
Java 1.8 update 152

**Comment by JLLeitschuh** [comment] 2017-11-27 17:24
Let me just start by saying that this is a pretty weird project setup.


I don't think that you need the `evaluationDependsOn(":parent:b")` line.

I'm not certain if this is enabled by default but you may want to try making sure that `org.gradle.configureondemand=false` is set.

Because of: https://github.com/gradle/gradle/issues/1630

**Comment by NikolayMetchev** [comment] 2017-11-27 17:28
In the attached project org.gradle.configureondemand=false (the default) and the bug still reproduces. I am aware of that other bug and this is not that.
I do need the evaluationDependsOn(":parent:b") line because evaluation is done alphabetically and I need b to be evaluated before a.

**Comment by JLLeitschuh** [comment] 2017-11-27 17:37
If I remove the `evaluationDependsOn(":parent:b")` then the project compiles fine.
I recommend that you depend upon artifacts produced by `:parent:b` using the gradle `configuration` artifacts instead of depending upon the evaluation of the entirety of `:parent:b` before `a` can run.

Do you have this problem in a project written in `groovy` or only in a project written in the Gradle Kotlin DSL?

**Comment by NikolayMetchev** [comment] 2017-11-27 17:43
The project I have is in Gradle Kotlin DSL. In my project I have more code which traverses the dependency tree. If I do that in A before B has been evaluated then I get incorrect results, hence I need b to be evaluated before a. If b is not a child project then all this works fine as well (I have for now resorted to not having child projects). This is less than ideal.

**Comment by eskatos** [comment] 2018-01-18 17:58
Related to #311

**Comment by eskatos** [comment] 2018-01-31 20:59
This is an issue in upstream configuration on demand / evaluationDependsOn impl.
Consider escalating upstream.

**Comment by NikolayMetchev** [comment] 2018-02-01 21:30
@eskatos Is that last comment aimed at me? Are you saying that if I wrote this example in Groovy this problem will not happen?

**Comment by bamboo** [comment] 2018-02-01 21:34
@NikolayMetchev The comment was not aimed at you. It was documenting our conclusion that the current Kotlin DSL behaviour is a symptom of a Gradle core issue.

**Comment by NikolayMetchev** [comment] 2018-02-01 21:35
@bamboo Thanks. Good luck.

**Comment by hzsweers** [comment] 2018-03-02 17:09
This happens even with parallel and configureondemand disabled. It also breaks indexing of dependencies in projects. Pretty much makes kotlin gradle DSL a non-starter in a nontrivial project in my experience trying to integrate it

`evaluationDependsOn` also doesn't appear to resolve the issue

example case: https://github.com/hzsweers/CatchUp/tree/ecfef0bb8db59e3ba6beeacc459862256bb0c1fe

builds fine, but if you sync in android studio, it fails with that message

**Comment by eskatos** [comment] 2018-03-22 09:16
Here is a minimal reproducer:

```kotlin
// settings.gradle.kts
include(":a", ":b:c")
```
```kotlin
// a/build.gradle.kts
evaluationDependsOn(":b:c")
```
```kotlin
// b/c/build.gradle.kts
plugins { base }
```
Configuring the build fails with:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':a'.
> A problem occurred configuring project ':b:c'.
   > org.gradle.api.internal.initialization.DefaultClassLoaderScope@497f1bf1 must be locked before it can be used to compute a classpath!
```
https://scans.gradle.com/s/odzx6nrwjsggi/

Interestingly enough, if you rename the `:a` project to say `:d` then the build succeeds.

**Comment by eskatos** [comment] 2018-03-23 14:42
The root cause is https://github.com/gradle/gradle/issues/4823

To work around the issue you can declare evaluation dependency from children projects to their parent.  Doing this in the root project that is always evaluated first should do.

Here is the same example as the minimal reproducer build above but including the work around:

```kotlin
// settings.gradle.kts
include(":a", ":b:c")

// build.gradle.kts
project(":b:c").evaluationDependsOn(":b") // HERE

// a/build.gradle.kts
evaluationDependsOn(":b:c")

// b/c/build.gradle.kts
plugins { base }
```

It can also be expressed more generally:
```kotlin
// build.gradle.kts
subprojects { parent!!.path.takeIf { it != rootProject.path }?.let { evaluationDependsOn(it)  } }
```

Note that this workaround completely defeat configuration-on-demand by forcing all subprojects evaluation.

Closing as superseded by https://github.com/gradle/gradle/issues/4823

**Closed by eskatos** 2018-03-23 14:42 UTC
Labels: a:bug
