### ISSUE TITLE
"Failed to compile accessors" adding extension to buildSrc plugin (v1.0 RC3)

### ISSUE THREAD

**Issue by eriwen** [gradle/kotlin-dsl#1062] opened 2018-08-24 18:28 UTC
### Expected Behavior
I should be able to add an extension to the buildSrc-plugin example as is done in the 1.0 RC release notes and use it.

### Current Behavior
However, when I try this I get "Failed to compile accessors."

Build Scan: https://scans.gradle.com/s/3jil2wl3rkxlg

Failure repro: Checkout https://github.com/gradle/kotlin-dsl/tree/ew/broken-buildSrc-extension/samples/buildSrc-plugin && run `./gradlew tasks`

**Comment by bamboo** [comment] 2018-08-24 18:39
This is a duplicate of #1051 fixed in b45aea4cff215dd0e7cb07fc8ff44ff2fdf08dec.

**Closed by bamboo** 2018-08-24 18:39 UTC
