### ISSUE TITLE
Intellij is falsely reporting that it can't find the following FixCrLfFilter.CrLf nested static class

### ISSUE THREAD

**Issue by flstaats** [gradle/kotlin-dsl#434] opened 2017-07-21 05:17 UTC
In Gradle Kotlin-DSL build.gradle.kts scripts Intellij is falsely reporting that it can't find the following FixCrLfFilter.CrLf nested static class.  This code runs properly at build time from the command line (we often use the builtin Ant filters in Copy scripts in our builds):

```
import org.apache.tools.ant.filters.FixCrLfFilter
...
val processResources by tasks.creating(Copy::class) {
   // TODO: Issue with Intellij not detecting FixCrLfFilter.CrLf static class, builds fine
   filter<FixCrLfFilter>("eol" to FixCrLfFilter.CrLf.newInstance("lf"))
}
```

This behavior was noted with the latest nightly gradle-kotlin-dsl-4.1-20170712173431+0000-all.zip on Intellij IDEA 2017.2 Build #IC-172.3317.76 using the built in JRE 1.8 & JDK 1.8.121 64-bit on both Windows and Linux.

**Comment by flstaats** [comment] 2017-07-21 14:41
Using Kotlin Intellij Plugin 1.1.3-release-IJ2017.2-2

**Comment by eskatos** [comment] 2017-07-25 08:47
Works for me, IntelliJ knows the inner static class and I can navigate to its source.

@flstaats any chance you could setup a small project that reproduce the issue?

**Comment by eskatos** [comment] 2017-07-25 08:50
Mmm, and after a refresh of the Gradle project I can now reproduce it.

![image](https://user-images.githubusercontent.com/132773/28563679-f8bf86cc-7126-11e7-9896-e63dca7e75ec.png)

Weird.

@flstaats you can ignore my previous comment.

**Comment by JLLeitschuh** [comment] 2017-07-28 15:22
Duplicate of #417

**Comment by eskatos** [comment] 2017-08-08 09:03
Closing as duplicate of #417

**Closed by eskatos** 2017-08-08 09:03 UTC
Labels: was:duplicate
