### ISSUE TITLE
Intellij is reporting false ERROR with tasks.getting that DeployTask from the com.xebialabs.xl-deploy plugin is not a subtype of Task

### ISSUE THREAD

**Issue by flstaats** [gradle/kotlin-dsl#435] opened 2017-07-21 05:22 UTC
In Gradle Kotlin-DSL build.gradle.kts scripts Intellij is reporting an ERROR with tasks.getting that DeployTask from the com.xebialabs.xl-deploy 0.4.0 plugin is not a subtype of Task.  It is and this code runs at build time from the command line:

```
// TODO: Intellij false warning that DeployTask not subtype of Task, builds from the command line
val deploy by tasks.getting(DeployTask::class) { ... }
```

This behavior was noted with the latest nightly gradle-kotlin-dsl-4.1-20170712173431+0000-all.zip on Intellij IDEA 2017.2 Build #IC-172.3317.76 using the built in JRE 1.8 & JDK 1.8.121 64-bit on both Windows and Linux.

**Comment by flstaats** [comment] 2017-07-21 14:38
This seems similar to #417

**Comment by flstaats** [comment] 2017-07-21 14:40
Kotlin Intellij Plugin 1.1.3-release-IJ2017.2-2

**Comment by JLLeitschuh** [comment] 2017-07-28 14:27
Duplicate of #417

**Comment by bamboo** [comment] 2018-01-17 17:20
Closing as duplicate.

**Closed by bamboo** 2018-01-17 17:20 UTC
