### ISSUE TITLE
Add simple handling for collection of dependencies for to start with.

### ISSUE THREAD

**Issue by soberich** [gradle/kotlin-dsl#1371] opened 2019-04-14 10:59 UTC
This seems to be a long requested feature.
referring to:
https://github.com/gradle/kotlin-dsl/issues/639
https://github.com/gradle/kotlin-dsl/issues/1187
https://github.com/gradle/kotlin-dsl/pull/1315
https://github.com/gradle/kotlin-dsl/issues/1369
https://github.com/gradle/gradle/issues/7649

Maybe for to already start with just add
on [kotlin-dsl](https://github.com/gradle/kotlin-dsl) side in (generated) accessors... (of course we could add it in own project)
```kotlin
fun DependencyHandler.`implementation`(vararg dependencyNotation: Any): Collection<Dependency?> =
    dependencyNotation.map { add("implementation", it) }
```

Instead of (as we do it now)
```gradle
    arrayOf(
        Deps.Libs.EBEAN,
        Deps.Libs.EBEAN_QUERY,
        Deps.Libs.EBEAN_QUERY_GEN,
        Deps.Libs.EBEAN_TEST,
        Deps.Libs.JSON_PATCH,
        Deps.Libs.JACKSON_COREUTILS,
        Deps.Libs.HIKARI,
        Deps.Libs.JACKSON_MONEY,
        Deps.Libs.ZALANDO_PROBLEM,
        Deps.Libs.ZALANDO_PROBLEM_JACK
    ).forEach(::implementation)
```
to finally have the desired 
```gradle
    implementation(
        Deps.Libs.EBEAN,
        Deps.Libs.EBEAN_QUERY,
        Deps.Libs.EBEAN_QUERY_GEN,
        Deps.Libs.EBEAN_TEST,
        Deps.Libs.JSON_PATCH,
        Deps.Libs.JACKSON_COREUTILS,
        Deps.Libs.HIKARI,
        Deps.Libs.JACKSON_MONEY,
        Deps.Libs.ZALANDO_PROBLEM,
        Deps.Libs.ZALANDO_PROBLEM_JACK
    )
```
I understand there could be caveats with non-string based declarations and configuration actions supplied, but for now seem like a viable solution, having in mind that this feature is on the horizon very long time.

**Comment by JLLeitschuh** [comment] 2019-04-15 15:34
I think this is a duplicate of gradle/gradle#7649 and any discussion should happen there.

**Comment by soberich** [comment] 2019-04-20 11:01
@JLLeitschuh I think this(this raised issue) relates to `kotlin-dsl`. It is all about exactly kotlin-dsl and not groovy for example. It is also literally adout DSL and not gradle functioning. Also, as I mentioned, comparing to other mentioned issues/prs, I propose to actually implement a "quick fix" to get it running and not to discuss again a bigger picture of how properly it should be in, say, gradle apis at first and then, possibly be ported (of needed poring) to kotlin-dsl.

**Comment by eskatos** [comment] 2019-04-24 11:35
Adding a "quick fix" to the Kotlin DSL might get in the way of doing it uniformly at the API level later.

If it is added to the API then it means that build logic in Groovy, Kotlin and other language will be able to discover and type-check the usage uniformly, for the better.

Let's push the discussion forward in https://github.com/gradle/gradle/issues/7649

**Closed by eskatos** 2019-04-24 11:35 UTC
