### ISSUE TITLE
Multi-project Build ->  Project lib dependencies

### ISSUE THREAD

**Issue by ozodrukh** [gradle/kotlin-dsl#400] opened 2017-06-25 09:40 UTC
Trying to follow [Multi-project Build](https://docs.gradle.org/3.3/userguide/multi_project_builds.html#sec:project_jar_dependencies)

Having **4** modules included in _settings.gradle_

and configure sub projects dependencies, and it fails to resolve configuration `compile`

```kotlin
// file: build.gradle.kts

allprojects {
    group = "co.watchlab:watches-service"
    version = "1.0"

    repositories {
        mavenCentral()
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

plugins {
    base
    java
}

subprojects {
    repositories {
        mavenCentral()
    }
    dependencies {
        testCompile("junit:junit:4.12")
    }
}

dependencies {
    // Make the root project archives configuration depend on every subproject
    subprojects.forEach {
        archives(it)
    }
}


```
 
### Output

<img width="652" alt="screen shot 2017-06-25 at 2 39 11 pm" src="https://user-images.githubusercontent.com/3184950/27515050-1a8201ac-59b4-11e7-89a9-659f535f91f2.png">

**Comment by sbuettner** [comment] 2017-07-24 13:52
Having the same issue in a multi project build.

**Comment by bamboo** [comment] 2017-07-24 13:58
Hi @ozodrukh, that's expected since no language plugin has been applied to the sub-projects.

**Comment by sbuettner** [comment] 2017-07-25 06:40
@bamboo I am still seeing this issue despite of having
```
subprojects {
	buildscript {
		dependencies { classpath(kotlin("gradle-plugin")) }
		repositories { jcenter() }
	}

	plugins {
		id("org.jetbrains.kotlin.jvm") version "1.1.3-2"
	}
      
	dependencies {
		"compile"(kotlin("stdlib"))
		"compile"(kotlin("reflect"))
	}
}
``` 
in the base project.

**Comment by JLLeitschuh** [comment] 2017-07-28 15:26
You dropped:
```kotlin
repositories {
    mavenCentral()
}
```
from your `subprojects` block in your last example. Is that causing your problem?

**Comment by ozodrukh** [comment] 2017-07-28 17:16
ooh, got it guys, thanks

**Comment by sbuettner** [comment] 2017-08-02 07:44
@JLLeitschuh Sadly not. 
```
	repositories {
		jcenter()
		mavenCentral()
		maven { setUrl("https://repo.spring.io/milestone") }
		maven { setUrl("https://repo.spring.io/snapshot") }
	}
``` 
is also present in the `subprojects` block.

**Comment by sbuettner** [comment] 2017-08-02 07:58
It seems like it doesnt work when using the plugins syntax like this:
```
plugins {
  id("org.jetbrains.kotlin.jvm") version "1.1.3-2"
}
```

It works when I change it to:
```
apply {
  plugin("org.jetbrains.kotlin.jvm")
}
```

@JLLeitschuh is that the intended behavior?

**Comment by JLLeitschuh** [comment] 2017-08-02 11:31
I think so, the semantics of the two blocks are different:
https://stackoverflow.com/a/32353244/3708426

**Comment by sbuettner** [comment] 2017-08-02 12:09
@JLLeitschuh Thanks, was not aware that difference. It was not obvious when looking at the sample projects. Should I add one?

**Comment by JLLeitschuh** [comment] 2017-08-02 12:19
@bamboo question for you, I think

**Comment by eskatos** [comment] 2018-01-17 18:01
Closing as answered

**Closed by eskatos** 2018-01-17 18:01 UTC
Labels: a:question
