### ISSUE TITLE
Cannot set "distributionType" for "Wrapper" task

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/kotlin-dsl#438] opened 2017-07-21 17:56 UTC
## build.gradle:
```
task wrapper(type: Wrapper) {
  gradleVersion = "4.1-rc-1"
  distributionType = Wrapper.DistributionType.ALL
}
```

## build.gradle.kts
```
task<Wrapper>("wrapper") {
  gradleVersion = "4.1-rc-1"
}
```

This does not work:
```
task<Wrapper>("wrapper") {
  gradleVersion = "4.1-rc-1"
  distributionType = Wrapper.DistributionType.ALL
}
```

**Comment by jaredsburrows** [comment] 2017-07-24 15:45
@bamboo Am I missing something here?

**Comment by bamboo** [comment] 2017-07-24 18:19
@jaredsburrows I need more details. What error do you get when you run `./gradlew wrapper`?

**Comment by jaredsburrows** [comment] 2017-07-24 19:45
@bamboo It "does" work but the IDE gives the following complaint:
<img width="932" alt="screen shot 2017-07-24 at 12 44 52 pm" src="https://user-images.githubusercontent.com/1739848/28541484-038889b4-706e-11e7-9013-99a53612c55f.png">

**Comment by bamboo** [comment] 2017-07-24 20:41
@jaredsburrows I cannot reproduce it with a simple project, there must be something else going on here:

![screen shot 2017-07-24 at 17 36 45](https://user-images.githubusercontent.com/51689/28543653-d2bdc2da-7096-11e7-81b3-c3b52b568c9c.png)

Could you provide a minimal script that reproduces the issue with IntelliJ IDEA 2017.2?

**Comment by jaredsburrows** [comment] 2017-07-24 22:31
@bamboo Sure.

Here is the project: https://github.com/jaredsburrows/android-gif-example

Here is the branch: https://github.com/jaredsburrows/android-gif-example/tree/build.gradle.kts

Here is the example wrapper code: https://github.com/jaredsburrows/android-gif-example/blob/build.gradle.kts/gradle/wrapper.gradle.kts#L1

**Comment by JLLeitschuh** [comment] 2017-07-28 15:15
You are missing:
```kotlin
import org.gradle.api.tasks.wrapper.Wrapper
```
That import isn't included in the default import set.

**Comment by jaredsburrows** [comment] 2017-07-28 18:26
@JLLeitschuh Does it work out the box for you?

I have reimported the project and it is still giving me problems.

<img width="570" alt="screen shot 2017-07-28 at 11 26 02 am" src="https://user-images.githubusercontent.com/1739848/28731145-96fe4d20-7387-11e7-8bca-ed275564059b.png">

**Comment by JLLeitschuh** [comment] 2017-07-28 20:07
Sounds like this may be caused by #417

Try:
```kotlin
import org.gradle.api.tasks.wrapper.Wrapper.DistributionType
task<Wrapper>("wrapper") {
  gradleVersion = "4.1-rc-1"
  distributionType = DistributionType.ALL
}
```

This seems very strange though. With the setup you have (without adding my changes), try clearing your IntelliJ cache and restarting. That may cause the import to get resolved.

If not try my suggestion above.

As to my setup, I don't have my wrapper task configured in its own file. My wrapper task configuration lives in my root `build.gradle.kts` file.

**Comment by eskatos** [comment] 2017-08-08 09:07
Closing as duplicate of #417

**Closed by eskatos** 2017-08-08 09:07 UTC
Labels: was:duplicate
