### ISSUE TITLE
resolutionStrategy in settings.gradle is not working

### ISSUE THREAD

**Issue by xmlking** [gradle/kotlin-dsl#547] opened 2017-10-14 17:55 UTC
resolutionStrategy in settings.gradle is not working

### How to reproduce: 

```
# remove  the gradle cache and try any gradle command
rm -fR  ~/.gradle/caches
git clone https://github.com/sdeleuze/spring-kotlin-fullstack
gradle build
```
More details are here:

https://github.com/sdeleuze/spring-kotlin-fullstack/issues/1

[Configuring-Plugins](https://github.com/gradle/kotlin-dsl/blob/master/doc/getting-started/Configuring-Plugins.md) documentation will **only** works if the plugin dependencies are already in Gradle's  local cache.

**Comment by JLLeitschuh** [comment] 2017-10-16 13:16
Can you provide a minimal example?

**Comment by xmlking** [comment] 2017-10-21 23:30
please see test with this repo:

https://github.com/xmlking/microservices-observability

#### How to reproduce:
```bash
# remove  the gradle cache 
rm -fR  ~/.gradle/caches
# and try any gradle command with in this project e.g., 
cd microservices-observability
gradle clean
```

**Comment by eskatos** [comment] 2017-10-25 09:02
Thanks for the report @xmlking 
This issue also apply to the Groovy DSL, it's a general Gradle problem.
This is a duplicate of https://github.com/gradle/gradle/issues/3210

**Closed by eskatos** 2017-10-25 09:02 UTC
