### ISSUE TITLE
Support application of custom scripts to arbitrary classes

### ISSUE THREAD

**Issue by oakad** [gradle/kotlin-dsl#923] opened 2018-06-08 19:14 UTC
In certain build scenarios it is desirable to separate complex configuration items into separate files. Gradle/groovy supports such behaviour rather unobtrusively - custom object is passed to `project.apply` via `to` field and then the usual groovy closure evaluation rules apply. Those custom objects can be rather arbitrary, completely independent of gradle api.

At present, kotlin-dsl explicitly prohibits such behaviour: `KotlinScriptTargetFor` checks for one of 3 varieties of allowed target classes and throws exception on any other target. Moreover, the rest of the evaluation API is internal/private.

It will be really nice if some public Kotlin API was exposed, allowing users to precompile arbitrarily named kotlin scripts against arbitrary classes (implementing whatever interfaces/DSLs necessary). Without this, it would be impossible to forego using groovy, because currently only the groovy bit provides the required functionality.

A bit of illustration (example project structure):

- **build.gradle.kts**
- **settings.gradle.kts**
- **funny_user_applicable_object_config** // can be trivially applied to `FunnyUserObject` via groovy
- **funny_user_applicable_object_config.kts** // presently will be processed by groovy as well, but it will be much better if it could be passed to kotlin-dsl and made applicable to `FunnyUserObject`
- **funny_user_applicable_object_config.gradle.kts** // kotlin-dsl will pick this up on application but will refuse to apply it to `FunnyUserObject` because of explicit check in `KotlinScriptTarget` and lack of public evaluation API

**Comment by eskatos** [comment] 2018-06-20 13:41
Duplicate of #659

**Closed by eskatos** 2018-06-20 13:41 UTC
