### ISSUE TITLE
Cannot configure non-root extension 

### ISSUE THREAD

**Issue by ghost** [gradle/kotlin-dsl#375] opened 2017-05-28 05:41 UTC
I want to use the App Engine plugin from my build.gradle.kts but cannot access the "tools" extension that is registered.

In groovy script it is accessed like this:

appengine {
  tools {
    // Configure tools path here
  }
}

More details here:

https://discuss.kotlinlang.org/t/gradle-script-kotlin-configure-app-engine-plugin/2830

**Comment by eskatos** [comment] 2017-09-29 16:03
Duplicate of #457, closing

**Closed by eskatos** 2017-09-29 16:03 UTC
Labels: was:duplicate
