### ISSUE TITLE
Top-level extensions of *ObjectContainer type should get the "invoke" style DSL

### ISSUE THREAD

**Issue by mkobit** [gradle/kotlin-dsl#761] opened 2018-03-15 21:29 UTC
### Expected Behavior

Should be able to use them like other top level containers like `ConfigurationContainer` and also have parity to Groovy.

### Current Behavior

Have to do workaround demonstrated in https://github.com/gradle/kotlin-dsl/issues/459

### Context

Using container-types in plugins as top level types for better DSLs.

### Steps to Reproduce (for bugs)

Don't have full setup right now but here is a close-to example

1. Add a `buildSrc` plugin/`java-gradle-plugin` ceremony

    ```kotlin
    import org.gradle.api.Named
    import org.gradle.api.NamedDomainObjectContainer
    import org.gradle.api.Plugin
    import org.gradle.api.Project
    import org.gradle.api.reflect.TypeOf
    
    open class MkobitExample : Plugin<Project> {
      override fun apply(target: Project) {
        val myContainer = target.container(MyType::class.java)
        target.extensions.add("withoutType", myContainer)
        val type = object : TypeOf<NamedDomainObjectContainer<MyType>>() {}
        target.extensions.add(type,"withType", myContainer)
      }
    }
    
    data class MyType(private val myName: String) : Named {
      override fun getName(): String = myName
    }
    ```

2. Add in consumption to root `build.gradle.kts`

    ```kotlin
    plugins {
      id("mktest")
    }
    withoutType {
      "hello" {
    
      }
    }
    
    withType {
      "hi" {
    
      }
    }
    ```

```
e: /home/mkobit/dotfiles/build.gradle.kts:148:7: Expression '"hello"' of type 'String' cannot be invoked as a function. The function 'invoke()' is not found
e: /home/mkobit/dotfiles/build.gradle.kts:154:7: Expression '"hi"' of type 'String' cannot be invoked as a function. The function 'invoke()' is not found


FAILURE: Build failed with an exception.

* Where:
Build file '/home/mkobit/Workspace/code_lab/example/build.gradle.kts' line: 148

* What went wrong:
Script compilation errors:

  Line 148:       "hello" {
                  ^ Expression '"hello"' of type 'String' cannot be invoked as a function. The function 'invoke()' is not found

  Line 154:       "hi" {
                  ^ Expression '"hi"' of type 'String' cannot be invoked as a function. The function 'invoke()' is not found
```

### Your Environment

Gradle 4.6 

 * Build scan URL:

**Comment by eskatos** [comment] 2018-08-14 16:05
`MyType` being in the default package, the root cause is #807 
Closing as duplicate

**Closed by eskatos** 2018-08-14 16:05 UTC
