### ISSUE TITLE
Documentation about ways to configure kotlin-dsl APIs. "Best practices" guide on that.

### ISSUE THREAD

**Issue by soberich** [gradle/kotlin-dsl#926] opened 2018-06-13 13:54 UTC
### Expected Behavior
A complete guide on per theme basis e.g. possible / recomended ways to create / get / configure plugins / tasks / other APIs

### Current Behavior
Information spread through source-code and examples. Constantly changing.

### Context
Some of the ways to configure, for example, `task` spread through `gradle/gradle` and `gradle/kotlin-dsl`
 source and ways to work with them are overwhelming.
Consider a guide.
Some ways which I "detected" are in the table. Some may not work and / or present.
A guide with "optimal" way would be great

<table>
    <col>
    <col>
    <col>
    <tr>
        <td>
        <td>old??</td>
        <td>new?? / recommended?? e.g. &quot;better&quot;</td>
    </tr>
    <tr>
        <td colspan=3>CREATE</td>
    </tr>
    <tr>
        <td rowspan=2>with name</td>
        <td>val task by tasks.creating {}</td>
        <td>
    </tr>
    <tr>
        <td>tasks.create(&quot;a&quot;) {}</td>
        <td>
    </tr>
    <tr>
        <td rowspan=2>with type</td>
        <td>val task by tasks.creating(A::class.java) {}</td>
        <td>
    </tr>
    <tr>
        <td>tasks.create( &quot;a&quot;, A::class.java) {}</td>
        <td>tasks.create&lt;A&gt;(&quot;a&quot;)</td>
    </tr>
    <tr>
        <td>
        <td colspan=2>lazy</td>
    </tr>
    <tr>
        <td>with name</td>
        <td>
        <td>tasks.createLater(&quot;a&quot;) {}</td>
    </tr>
    <tr>
        <td rowspan=2>with type</td>
        <td rowspan=2>
        <td>tasks.register(A::class.java, &quot;a&quot;) {}</td>
    </tr>
    <tr>
        <td>tasks.createLater(&quot;a&quot;, A::class.java) {}</td>
    </tr>
    <tr>
        <td colspan=3>GET</td>
    </tr>
    <tr>
        <td>with name</td>
        <td>tasks[&quot;a&quot;] {}</td>
        <td>
    </tr>
    <tr>
        <td rowspan=2>with type</td>
        <td>tasks.getByName&lt;A&gt;(&quot;a&quot;) {}</td>
        <td>
    </tr>
    <tr>
        <td>val a: A by tasks {}</td>
        <td>
    </tr>
    <tr>
        <td colspan=3>CONFIGURE</td>
    </tr>
    <tr>
        <td>with name</td>
        <td>tasks[&quot;a&quot;].configure {}</td>
        <td>tasks.named(&quot;a&quot;) {}</td>
    </tr>
    <tr>
        <td>with type</td>
        <td>tasks.withType(A::class.java) {}</td>
        <td>tasks.withType&lt;A&gt; {}</td>
    </tr>
    <tr>
        <td>
        <td colspan=2>lazy</td>
    </tr>
    <tr>
        <td>with name</td>
        <td>
        <td>tasks.named(&quot;a&quot;).configure {}</td>
    </tr>
    <tr>
        <td>with type</td>
        <td>
        <td>tasks.withType&lt;A&gt;().configureEach {}</td>
    </tr>
</table>

Which ones to use (better)?

**Comment by soberich** [comment] 2018-06-13 13:55
a table, just in case
```html
<table>
    <col>
    <col>
    <col>
    <tr>
        <td>
        <td>old??</td>
        <td>new?? / recommended?? e.g. &quot;better&quot;</td>
    </tr>
    <tr>
        <td colspan=3>CREATE</td>
    </tr>
    <tr>
        <td rowspan=2>with name</td>
        <td>val task by tasks.creating {}</td>
        <td>
    </tr>
    <tr>
        <td>tasks.create(&quot;a&quot;) {}</td>
        <td>
    </tr>
    <tr>
        <td rowspan=2>with type</td>
        <td>val task by tasks.creating(A::class.java) {}</td>
        <td>
    </tr>
    <tr>
        <td>tasks.create( &quot;a&quot;, A::class.java) {}</td>
        <td>tasks.create&lt;A&gt;(&quot;a&quot;)</td>
    </tr>
    <tr>
        <td>
        <td colspan=2>lazy</td>
    </tr>
    <tr>
        <td>
        <td>
        <td>tasks.createLater(&quot;a&quot;) {}</td>
    </tr>
    <tr>
        <td rowspan=2>with type</td>
        <td rowspan=2>
        <td>tasks.register(A::class.java, &quot;a&quot;) {}</td>
    </tr>
    <tr>
        <td>tasks.createLater(&quot;a&quot;, A::class.java) {}</td>
    </tr>
    <tr>
        <td colspan=3>GET</td>
    </tr>
    <tr>
        <td>with name</td>
        <td>tasks[&quot;a&quot;] {}</td>
        <td>
    </tr>
    <tr>
        <td rowspan=2>with type</td>
        <td>tasks.getByName&lt;A&gt;(&quot;a&quot;) {}</td>
        <td>
    </tr>
    <tr>
        <td>val a: A by tasks {}</td>
        <td>
    </tr>
    <tr>
        <td colspan=3>CONFIGURE</td>
    </tr>
    <tr>
        <td>with name</td>
        <td>tasks[&quot;a&quot;].configure {}</td>
        <td>tasks.named(&quot;a&quot;) {}</td>
    </tr>
    <tr>
        <td>with type</td>
        <td>tasks.withType(A::class.java) {}</td>
        <td>tasks.withType&lt;A&gt; {}</td>
    </tr>
    <tr>
        <td>
        <td colspan=2>lazy</td>
    </tr>
    <tr>
        <td>with name</td>
        <td>
        <td>tasks.named(&quot;a&quot;).configure {}</td>
    </tr>
    <tr>
        <td>with type</td>
        <td>
        <td>tasks.withType&lt;A&gt;().configureEach {}</td>
    </tr>
</table>
```

**Comment by thc202** [comment] 2018-06-13 14:18
This seems to be a duplicate of #818.

**Comment by StefMa** [comment] 2018-06-13 17:04
Yes, #818 is one part.
There is already another ticket see https://github.com/gradle/kotlin-dsl/issues/880 to fix that.
There is also a translate guide in the making: https://github.com/gradle-guides/migrating-build-logic-from-groovy-to-kotlin

So I think just stay tuned for such a table ;)

**Closed** 2018-06-14 10:06 UTC
