### ISSUE TITLE
<reified T : Plugin<Project>> Project.apply() should use Plugin<out Project> as bound

### ISSUE THREAD

**Issue by Dico200** [gradle/kotlin-dsl#982] opened 2018-07-25 21:37 UTC
https://github.com/gradle/kotlin-dsl/blob/0eccacca4c9f87be19dd88045c2007ae3ee58f2f/subprojects/provider/src/main/kotlin/org/gradle/kotlin/dsl/ProjectExtensions.kt#L78-L79

The type parameter has a lower bound in `Plugin<Project>`. This is because we want to only apply Plugins for Projects. Alright.
So for example, we have `KotlinPlatformJvmPlugin` which inherits `Plugin<Project>`. For this plugin, we can use the aforementioned method to apply it to a project.

There's also `JavaPlugin` which is, for a reason unknown to me, is a `Plugin<ProjectInternal>`, where `ProjectInternal` extends `Plugin`.
We can't use the aforementioned apply method to apply this plugin to a project now.

While I understand the concept of kotlin's declaration site variance and type projection, I don't really know how to explain why the declaration of `apply` should use an upper bound of `Plugin<out Project>` in T. I tested it though and the compiler allows you to `apply<JavaPlugin>` with this change.

**Comment by mkobit** [comment] 2018-07-25 22:08
Similar to https://github.com/gradle/kotlin-dsl/issues/964 (which led to https://github.com/gradle/gradle/issues/5964) and https://github.com/gradle/kotlin-dsl/pull/965

**Comment by eskatos** [comment] 2018-07-26 08:52
Duplicate of #964
Superseded by  gradle/gradle#5964
Closing

**Closed by eskatos** 2018-07-26 08:52 UTC
Labels: was:duplicate, was:superseded
